### ISSUE TITLE
Relocating batches default selections (steveroland)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#493] opened 2015-10-16 12:04 UTC
Issue reported by **steveroland** at 2015-10-16 12:04:20 UTC
Time: 2015-10-16T11:57:07+00:00
Session ID: a5ca698a0781a839dba8ee12cc4d4cac
Problem Page URL: [/freereg1_csv_files/5620574df493fd6ba5007f60/relocate](/freereg1_csv_files/5620574df493fd6ba5007f60/relocate)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/5620574df493fd6ba5007f60](http://www.freereg.org.uk/freereg1_csv_files/5620574df493fd6ba5007f60)
Reported Issue:
When relocating a batch, it would be helpful if the page of selections came up pre-filled with the current ones. Usually you are only changing the register type, but have to re-select everything (country, place, church ....) These are highly unlikely to ever be changed for a batch.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444997059-54594-9126/Capture.jpg)

**Comment by Captainkirkdawson** [comment] 2015-10-17 17:24
Steve

You only get those additional options because you are a data manager. The
data managers are the only people who can relocate batches between
countries and counties but will look at defaults down the road

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment] 2015-10-18 00:34
OK thanks Kirk.

Steve

**Comment by Captainkirkdawson** [comment] 2016-10-16 23:42
Duplicate of 561

**Closed as completed** 2016-10-16 23:42 UTC
