### ISSUE TITLE
43229465 Messages being sent to emails that are not on the server (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#754] opened 2016-05-15 08:22 UTC
Issue reported by **REGManager** at 2016-05-15 08:11:05 UTC
Time: 2016-05-15T08:07:09+00:00
Session ID: f24e0dfcf5b612ec70629c57dc0a0cd3
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/contacts](http://www.freereg.org.uk/contacts)
Reported Issue:
I have had an email from Wendy Pusey email address wendy@puseyuk.co.uk that she received my message #43227690.

She is not Active and her email address is not on the server.  The wrong UserID list would seem to be being used.

Eric

PS.  I have edited this UserID in Test3 just in case this list of UserIDs is being used.  This person is getting a bit annoyed as she has asked a number of time to be removed.  Her UserID is still there but not active and with my email address.

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2016-05-15 14:25
This cannot be 1.3

**Comment by edickens** [comment] 2016-05-15 14:48
```
So what is it?  I still don't understand what to put when there is
an issue not associated with the version being developed.  This is
not a "Researcher's enhancement".  I think it is a serious problem
because I've had quite a few complaints that their request to be
taken off the distribution has not worked.

  This cannot be 1.3
  —
    You are receiving this because you are subscribed to this
    thread.
    Reply to this email directly or view
      it on GitHub
```

**Comment by PatReynolds** [comment] 2016-05-15 19:40
I have been using 1.3 as a placeholder for something else.  It means either
'urgent, and not in the FreeREG roadmap' (for example, cookie consent) or
'not a bug in the code, but something that should have arisen during
testing of an earlier phase, and didn't, and can't wait until the
appropriate phase'.  They need to be considered in prioritising work for
the current milestone, but are not leading to the achievement of the
current milestone.

Would 'Milestone None' work for these?

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940.  VAT
registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment] 2016-05-15 21:35
I am sorry to be difficult but 1.3 is gone and finished. If you want it in
the current release we are working on then assign it (in this case 1.4) and
urgent

**Comment by Captainkirkdawson** [comment] 2016-05-15 22:01
What was her userid? What syndicate was she in? I would need the original email  she received

There is no Wendy Pusey registered with FreeReg. There is no such email address.

There is an Active Userid  WendyT that has an email address wpusey@tiscali.co.uk. She stopped transcribing 6 years ago.

Did she change her name? Has she got wpusey@tiscali.co.uk. forwarding to  wendy@puseyuk.co.uk?

**Comment by PatReynolds** [comment] 2016-05-16 09:00
No worries - I've updated the two false 1.3 issues to 1.4.

**Comment by Captainkirkdawson** [comment] 2016-05-16 14:01
Have confirmed with Wendy that she did have a second Userid WendyT with the email address  wpusey@tiscali.co.uk. That email address is active as is that Userid.
Have made WendyT inactive.
There is no bug.

**Comment by edickens** [comment] 2016-05-16 14:11
```
Thanks Kirk,

What confused me is that the UserID WendyT is
  not for Wendy Pusey and was not the email address that she sent
  me.  So none of the searches found it.

  Did you just make it Inactive?  That is what was needed.

  Are you sure that the system is working correctly now, not that it
  ever wasn't I think!  In which case I will not change email
  addresses in future.

  Eric
```

**Comment by Captainkirkdawson** [comment] 2016-05-16 14:21
Yes I made WendyT inactive.

The system works as designed. It was not a system bug. It was doing what it was asked to do.

I found it by displaying all userids and using chrome find for wendy and then pusey thus finding the WendyT with that pusey email address.

Oh yea of little faith.

**Closed as completed** 2016-05-16 15:56 UTC
Labels: Urgent
