### ISSUE TITLE
Reduced number of files (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#509] opened 2015-10-21 09:28 UTC
Issue reported by **MikeNL** at 2015-10-21 09:28:31 UTC
Time: 2015-10-21T09:24:31+00:00
Session ID: f171419edec9acca3f13956e16d53321
Problem Page URL: [/freereg1_csv_files/selection?option=List%20by%20Number%20of%20Errors%20then%20Filename](/freereg1_csv_files/selection?option=List%20by%20Number%20of%20Errors%20then%20Filename)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/my_own](http://www.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
Your Actions: › My Batches Options › List of Batches
MikeNL (Sorted by number of errors)

The above list only gives batches entered by me in BKM. This only goes up to the letter "H" and there are many more that are not showing.

I have also transcribed records for NTH, HRT, WAR, CON and none of these are showing.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2015-10-21 15:03
Duplicate of 512 and 514

**Closed as completed** 2015-10-21 15:03 UTC
