### ISSUE TITLE
Teal background and Cookie consent at reduced screen widths (Was 264927518 Enhancement Suggestion (Leslie Poulton))

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1501] opened 2023-05-30 13:15 UTC
Issue reported by **Leslie Poulton** at 2023-05-25 06:58:38 UTC
Time: 2023-05-25T06:51:59+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Good morning

I am a current transcriber for FreeREG.  I also use this great tool for my own research.  It is great!  As a possible improvement, would you consider using a different background colour to the VIEW in a Search result?  I know that the dark teal colour is part of the logo, but it is very difficult to read all of the details when it is used as a full background colour.  Maybe the paler blue, if you need to use a logo colour.  Just a suggestion.

**Comment by AlOneill** [comment] 2023-05-30 14:11
Tried to understand the reported issue. I cannot see that teal is being used as the background colour to a search result.

But, I did spot this:

<img width="853" alt="Record_Details_574bad72f493fdf52f010c32___FreeREG_and_A6_Stalogy____June_2023_SETUP____2023_planner_setup_-_YouTube" src="https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/14852554/9210ca07-5330-4a72-8a0e-3569a8a493c1">

In other words, something in the body is not being closed properly or something similar, resulting in the margins being lost. I do not have the energy now to look more deeply, but will do so later if required.

**Comment by AlOneill** [comment] 2023-05-30 14:12
PS I was on test 3

**Comment by DeniseColbert** [comment] 2023-09-27 13:56
@SteveBiggs could you go back to Leslie and ask for screenshots of the issue?

**Comment by SteveBiggs** [comment] 2023-09-28 11:57
I believe this was only an issue on a smart phone and has now been fixed but will check with the OP.

**Comment by Vino-S** [comment] 2023-11-01 15:31
Sandra to contact Leslie

**Comment by ghost** [comment] 2023-11-02 10:19
Emailed Leslie this morning, awaiting reply.

**Comment by ghost** [comment] 2023-11-03 10:41
Leslie has replied there is no change - Leslie noted that it was a laptop she was using and not a phone.

**Comment by SteveBiggs** [comment] 2023-11-03 12:00
In that case, I think we need a screenshot of the problem as I see a white background. Perhaps also have Leslie tell us what browser and OS she's using?

**Comment by ghost** [comment] 2023-11-10 21:01
Will email Leslie and see if she can provide the info needed. I have emailed her this evening.

**Comment by ghost** [comment] 2023-11-22 14:43
![IMG_1903 (1)](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/20557838/30eeafa8-a010-44c3-85a2-a30874414565)
Leslie finally captures a screenshot of the teal she was talking about.

**Comment by DeniseColbert** [comment] 2023-11-22 15:14
@CommsCoord to advise Leslie to update her Firfox browser, and clear cookies and cache

@jayto581 to take a look at the teal in the footer 'bleeding' in the CSS

**Comment by jayto581** [comment] 2023-11-22 16:24
@CommsCoord @DeniseColbert @Vino-S @SteveBiggs 
I was able to reproduce the problem on Firefox, Chrome and Edge. The problem is caused when the browser width window is made too small. 

A temporary fix, is to increase the size of the browser width window to the point when the teal background disappears.

The cause is related to our CSS style sheet implementation for small screens. Further investigation is required to resolve the issue permanently.

**Comment by ghost** [comment] 2023-11-28 17:13
@jayto581 I think the photo she included showed a split screen. Could this be what is affecting our lady's PC?

**Comment by jayto581** [comment] 2023-11-29 14:56
@CommsCoord 
No, the split screen is not causing the problem. Anyone who has their Freereg screen too narrow will experience the same problem. A temporary workaround is to make the Freereg screen a little wider and everything should return to normal.

The problem is cause by how Freereg was programmed. The Freereg developers will need to look into it. Thanks for reporting the problem.

**Comment by DeniseColbert** [comment] 2023-12-05 15:45
@jayto581 identified that from 570px wide and lower, there is code that shouldn't be working in effect. Cookie consent, ad (affecting CEN too) and teal background (just REG). @Vino-S will take a look.

**Comment by Vino-S** [comment] 2024-01-17 14:24
REady for testing in test3

**Comment by DeniseColbert** [comment] 2024-01-17 15:17
Steve to test screen width issue

**Comment by SteveBiggs** [comment] 2024-01-17 16:12
Looks good now.

**Comment by DeniseColbert** [comment] 2024-04-10 14:38
Closing

**Closed as completed by DeniseColbert** 2024-04-10 14:38 UTC
Labels: Ready for Deployment
