### ISSUE TITLE
102771967 Image Groups Completed cannot be returned to CC (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1060] opened 2018-04-04 11:46 UTC
Issue reported by **steveroland** at 2018-04-04 11:46:07 UTC
Time: 2018-04-04T11:42:24+00:00
Session ID: 3200cbb4e266dd9ad7cd443c16f174ef
Problem Page URL: [/image_server_groups/5a9ec716f493fdbfcb98f0be/index](/image_server_groups/5a9ec716f493fdbfcb98f0be/index)
Previous Page URL: [https://www.freereg.org.uk/sources/5a9ec716f493fdbfcb98f0be?assignment_filter_list=&image_group_filter=](https://www.freereg.org.uk/sources/5a9ec716f493fdbfcb98f0be?assignment_filter_list=&image_group_filter=)
Reported Issue:
There are some groups with all images in status of Complete that I cannot return to CC and cannot unassign from the transcriber. Example is 2 groups for Angmering per attached image.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5ac4bafff493fd3c1e5a8724/Capture.GIF    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5ac4bafff493fd3c1e5a8724/Capture.GIF)

**Comment by SteveBiggs** [comment] 2018-04-04 11:49
The cause may be that I only allocated some of the images to the transcriber and marked the rest as Complete. So not all were "finished" by the transcriber. Now as CC I cannot accept them as complete so they remain with the syndicate and transcriber.

**Comment by richpomfret** [comment] 2018-04-09 15:10
@bev-fc can you take a look and see what you think? Perhaps a bug?

**Comment by bev-fc** [comment] 2018-04-09 17:18
@richpomfret a 'COMPLETE' image group (all images under the group has status COMPLETE) does not have the option to be allocated or rejected anymore.

my role on FREEREG production server is 'technical', I can not see image group related pages, I am not quite sure what's the current status of the involved assignments/transcribers, the answer is based on my guessing.

**Comment by Captainkirkdawson** [comment] 2018-04-09 17:38
@bev-fc  I believe that you should try to create the situation on your own test server using the process that @SteveBiggs documented above. I am sure he is willing to expand on what he did if required.
We should never go attempting to debug on the production servers.

**Comment by bev-fc** [comment] 2018-04-09 17:43
@Captainkirkdawson I can not figure out what happened based on what Steve or the originator described. 

@SteveBiggs  You mentioned " The cause may be that I only allocated some of the images to the transcriber and marked the rest as Complete", did you allocate some images to a transcriber, how did their status be changed to 'Complete' before you accept them? My understanding is you only set the status of unallocated images to complete. Can you help with detailed steps so I can reproduce it.

**Comment by SteveBiggs** [comment] 2018-04-09 18:11
I will try to reproduce the issue again in test2 later this evening and give precise steps.

**Comment by SteveBiggs** [comment] 2018-04-09 19:28
Trying to reproduce in test2, but I clicked Manage Syndicate then Manage Images and get this error page:
![image](https://user-images.githubusercontent.com/25303607/38518313-76116658-3c34-11e8-90e8-ea67c9b8e209.png)

**Comment by Captainkirkdawson** [comment] 2018-04-09 23:00
As noted in #1386 test2 is currently running a very up to date software package. This may be a result of that

**Comment by Captainkirkdawson** [comment] 2018-04-09 23:09
However it does appear that `sort_by': comparison of Array with Array failed  is a frequent issue. Often caused by one of the elements being nil

**Comment by Captainkirkdawson** [comment] 2018-04-09 23:11
@SteveBiggs  suggest you do the test on test3 at this time.

**Comment by bev-fc** [comment] 2018-04-10 18:06
@Captainkirkdawson I checked database on test2, the Church that the Image Group Cofton Hackett PR/WOR-CoftonHackett-BU-1813-1849 (and other image groups under the same Source) belongs to has no Registers, while the Register that the Source belongs to does not exist, this caused the error Steve received. Register in the middle disappeared, do you have any idea what can cause this?

**Comment by Captainkirkdawson** [comment] 2018-04-10 22:37
It can happen very easily in a test environment when code has failed during a test. Over time the database gets increasingly damaged. I am sure you have seen that in your own database. My own is barely usable. We do not take any steps to recreate the test database from scratch. My only surprise is that we do not see it more often. I will see if I can repair it.. But before I do was that the church that @SteveBiggs was working on.

**Comment by Captainkirkdawson** [comment] 2018-04-11 00:22
@SteveBiggs @bev-fc  I have rebuilt test2 with the latest collections from production including sources image_server_groups image_server_images AND assignments.
The  SSX syndicate now opens correctly. 
This will enable us to review the original issue reported by Steve at the start of this story

**Comment by SteveBiggs** [comment] 2018-04-11 12:55
On test2 I assigned part of the group; SSX-Poling-BA-1875-1900-150-1-2-1 to myself. Then under the Assignment I clicked 'Send Finish Email to SC'. Then as SC, I clicked 'AC' and got this error:

![image](https://user-images.githubusercontent.com/25303607/38617671-883ca020-3d8f-11e8-82c0-1a8291d3ab99.png)

but the group has been removed from the submitted list. I then selected 'List Fully Transcribed Groups' and got this error:

![image](https://user-images.githubusercontent.com/25303607/38617797-d08cf47e-3d8f-11e8-853c-847456143b16.png)

I'll try it on test3 later.

**Comment by richpomfret** [comment] 2018-04-11 16:20
Loks like this is a non-issue so closing.

**Comment by Captainkirkdawson** [comment] 2018-04-12 02:00
Why was this closed? Still very much an issue

**Comment by SteveBiggs** [comment] 2018-04-12 11:24
@Captainkirkdawson I said it can be closed because I think I misinterpreted what happens to groups once they are Complete. I assumed they would be removed from the syndicate when the CC accepted them as completed, but I now see that they all stay listed in the syndicate groups:
![image](https://user-images.githubusercontent.com/25303607/38674361-27ca0cf6-3e4c-11e8-8318-aafb49a82cc6.png)

So I don't believe there is a bug after all (unless they SHOULD be removed from the SC listing of allocated groups?)

**Comment by Captainkirkdawson** [comment] 2018-04-12 14:35
@SteveBiggs My concern was the need to address the 2 subsequent crashes you had. Research by @bev-fc has shown these relate to the software_update rather than the image server functionality.
What is your requirement wirt removal; unsure if we ever stated a requirement.

**Comment by SteveBiggs** [comment] 2018-04-12 15:03
When the SC clicks 'AC' to accept an assignment as finished, the assignment is removed from the transcriber's assignment list, but the transcriber's userid remains associated with the group - this is good.
So when the CC clicks 'Accept as Completed' for the image group, I would expect the syndicate name to stay associated with the group, but for it to be removed from the list of allocated groups for the SC.

**Comment by Captainkirkdawson** [comment] 2018-04-12 16:57
Have moved the crash issue to software_upgrade. Will leave open to complete decision on appropriate course of action on completion of assignment

**Comment by Captainkirkdawson** [comment] 2018-04-13 20:34
I agree with you on  "when the CC clicks 'Accept as Completed' for the image group, I would expect the syndicate name to stay associated with the group, but for it to be removed from the list of allocated groups for the SC."

**Comment by bev-fc** [comment] 2018-04-25 14:12
@Captainkirkdawson I found out I have to use branch software_update instead of master, now I have new version of rails running on my machine to continue with this ticket, I have a question before moving forward, does branch software_update have all codes the same as master? can I make changes in the copy from branch software_update? which branch should I follow now, is it software_update?

**Comment by Captainkirkdawson** [comment] 2018-04-25 14:52
@bev-fc The answer to the question is not as simple as you might hope and it depends on which aspect of this issue you are talking about. 

All servers EXCEPT vervet (test) are now running master on ruby 2.4.3 and rails 4.2.8 ; 

test3 on vervet is testing changes to master which will be deployed soon to fix most issues. So any feature augmentation or bug fix will done against master and use rails 4.2.8. This refers to this the specific issue of this story
"when the CC clicks 'Accept as Completed' for the image group, I would expect the syndicate name to stay associated with the group, but for it to be removed from the list of allocated groups for the SC."

test2 is running software_update which is the branch associated with the rails 5.2, ruby 2.4.3 and a large number of GEM updates. Only issues associated with that branch should be deployed to the software_update. It is not 100% uptodate with master. It will be merged into master when we are ready to deploy it.  So if you are talking about the "return_to back:" aspect initially found as part of this story and ONLY exists in that branch it has to be done against that branch ie software_update. Work on that should be reported in story 1386.  Do not attempt to merge master into software_update at this time there is no need to so do.

**Comment by bev-fc** [comment] 2018-04-25 14:58
@Captainkirkdawson I mean which branch of code on github should I use to make the changes before pushing the code to test2, master doesn't have the right gems version, if I use software_update, I can start rails with proper version but I do not know if this is the version of code I can use as base to make changes.

**Comment by Captainkirkdawson** [comment] 2018-04-25 15:05
@bev-fc  I thought I answered that question in my post. It depends on what changes you are trying to make and you have not said. Your server should be able to run either master or software_update

**Comment by bev-fc** [comment] 2018-04-25 15:08
@Captainkirkdawson the undefined method 'back_url' error Steve received, which is caused by new version of rails deprecated the use of redirect_to :back

**Comment by Captainkirkdawson** [comment] 2018-04-25 15:25
In which case you will work on using the software_update branch and report on story 1386

**Comment by bev-fc** [comment] 2018-04-26 12:38
@SteveBiggs Can you verify if it works on test2 this time?

@Captainkirkdawson I've updated issue [1386](https://github.com/FreeUKGen/MyopicVicar/issues/1386)

**Comment by SteveBiggs** [comment] 2018-04-26 12:50
On test2, as SC I clicked 'List Fully Transcribed Groups' and got this error:
![image](https://user-images.githubusercontent.com/25303607/39306657-ad4a2976-4958-11e8-9cec-bec405744042.png)

**Comment by SteveBiggs** [comment] 2018-04-26 12:53
Also 'List Fully Reviewed Groups':
![image](https://user-images.githubusercontent.com/25303607/39306852-26ebda4a-4959-11e8-9ef2-0dfb902f8d38.png)

**Comment by bev-fc** [comment] 2018-04-26 14:10
@SteveBiggs I am sorry about it, can you try it again?

**Comment by Captainkirkdawson** [comment] 2018-04-26 14:35
@bev-fc  this will take the user back too far see my comment on story 1386

**Comment by bev-fc** [comment] 2018-04-26 14:53
@Captainkirkdawson I think it stays on the correct page, as attached, I clicked 'List Fully Transcribed Group' under 'Manage Syndicates'.
![20180426_007](https://user-images.githubusercontent.com/22349799/39313403-e5cc6b7e-493f-11e8-875d-63ab796bc1f4.jpg)

**Comment by Captainkirkdawson** [comment] 2018-04-26 15:01
Bev remember what a fallback_location is. It is somewhere to go **if for some reason the correct link fails.**

**Comment by SteveBiggs** [comment] 2018-04-29 12:45
I am not seeing any crashes now so that's good thanks Bev.
Now we are just left with the issue of why Completed groups remain in the SC list of Allocated Image Groups. Once a group is marked Complete by the CC, it should no longer be allocated to the syndicate.

**Comment by bev-fc** [comment] 2018-04-29 16:15
@SteveBiggs I pushed the change, please take a look if the change fits what being asked.

**Comment by SteveBiggs** [comment] 2018-04-30 13:07
@bev-fc the completed IG has gone from the SC All Allocated list:

![image](https://user-images.githubusercontent.com/25303607/39428361-0025a110-4c7f-11e8-9c07-5d621277b941.png)

but when I select the Image Server and List Image Groups it is still there:

![image](https://user-images.githubusercontent.com/25303607/39428432-3a977f76-4c7f-11e8-8ae3-16671aecffe0.png)

I would expect it to no longer be visible to the SC at all once Complete.

**Comment by Captainkirkdawson** [comment] 2018-05-01 04:01
A fix applied to test3 by Bev

**Comment by SteveBiggs** [comment] 2018-05-01 10:34
Looks good now, thanks.

**Comment by richpomfret** [comment] 2018-05-09 15:53
Ready for deployment.

**Closed as completed** 2018-05-23 15:49 UTC
Labels: bug, Image Server

**Comment by SteveBiggs** [comment] 2018-05-23 18:52
Has this been deployed to production?

Steve


Stephen Biggs
FreeREG Chairman

**Comment by Captainkirkdawson** [comment] 2018-05-24 00:22
Not yet

**Comment by SteveBiggs** [comment] 2018-05-24 10:29
Strictly speaking it shouldn't be closed yet then - until verified in
production.

Steve


Stephen Biggs
FreeREG Chairman
