### ISSUE TITLE
183913589 duplicate batches? (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1386] opened 2020-10-29 17:59 UTC
Issue reported by **deo123** at 2020-10-29 15:06:29 UTC
Time: 2020-10-29T15:02:33+00:00
Session ID: 6253818bf47a5e6d2ee5f0b47a59990a
Problem Page URL: [/registers/5e8b2352f493fdfe6004e950?locale=en](/registers/5e8b2352f493fdfe6004e950?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/place_range?params=O-Q](https://www.freereg.org.uk/manage_counties/place_range?params=O-Q)
Reported Issue:
Hi,

yesterday one of my transcribers uploaded a batch and the system produce two batches, same time and number of records, see attachment.

I am not sure if this is a one off. I did put it by Steve first and told me to report the problem.

Regards
Doreen
https://www.freereg.org.uk/uploads/feedback/screenshot/5f9ada75f493fd63326904ef/for_Steve.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2020-10-29 18:12
Duplicate of one posted by @edickens

**Closed as completed by Captainkirkdawson** 2020-10-29 18:12 UTC
