### ISSUE TITLE
Website Problem (Fritha Hennessy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#218] opened 2015-04-23 16:04 UTC
Issue reported by **Fritha Hennessy** at 2015-04-23 16:04:01 UTC
Time: 2015-04-23T15:55:25+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts](http://www13.freereg.org.uk/contacts)
Reported Issue:
I try to save or print all my hits for future reference.  When trying to save to pdf (Opera and Chrome, Windows 7), the results are all overlaid, and can't be seen clearly; the same problem occurs when printing.  Sample screenshot (hopefully) attached.

Having said that, this is also a thank you.  I've managed to get more information here that I couldn't find in the original FreeReg.  I think you provide an amazing service.  

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1429805041-15946-0802/FreeReg2.jpg)

**Comment by Captainkirkdawson** [comment] 2015-04-23 16:29
Duplicate of 210

**Closed as completed** 2015-04-23 16:29 UTC
