### ISSUE TITLE
114462268 Cannot reply to my Feedbacks (Stephen) Needed by #1380

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1119] opened 2018-08-17 19:05 UTC
Priority (0 4 8 6) 18

depends on # 1380

Issue reported by **steveroland** at 2018-08-17 19:04:28 UTC
Time: 2018-08-17T19:00:40+00:00
Session ID: 7c2f6edd3944d84fbc8d9b943b5fdda8
Problem Page URL: [/feedbacks/5b640385f493fd432d61b85e/reply](/feedbacks/5b640385f493fd432d61b85e/reply)
Previous Page URL: [https://www.freereg.org.uk/feedbacks/userid_feedbacks](https://www.freereg.org.uk/feedbacks/userid_feedbacks)
Reported Issue:
I tried to reply to myself in order to remove a Feedback with no reply and it gave the "Something has gone wrong ...." error.
No doubt this problem report will create another Feedback that I can't reply to or remove!    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b771c3cf493fdaa5d4fca26/_old_)

Needed by #1380

**Comment by SteveBiggs** [comment] 2018-08-29 12:11
There is also a breadcrumbs issue. If as CC, I 'SH' one of my feedbacks, then click the breadcrumb 'Feedbacks', I am taken to the list of ALL Feedbacks that should not be visible to a CC.

I'm not sure what the purpose/benefit is of having these 'new feedbacks' and 'feedback with reply' notifications on the login page.

**Comment by Captainkirkdawson** [comment] 2018-10-23 16:16
Will address as part of #1629

**Comment by Captainkirkdawson** [comment] 2018-10-28 21:43
@SteveBiggs

WRT the red error. It was caused by attempting to access a document that did not exist. I have added a trap for that.

 I am puzzled by the next post relating to breadcrumbs. 
Feedbacks are not available to County/ country/ syndicate/ volunteer/  genealogy/  data managers.  Feedbacks are available to website/ contacts/ technical/ system admin/ project and executive managers as well as documentation/ engagement/ general communication coordinators (although why we include the latter 2 is a puzzle). Those that have access have access to ALL. There are no groupings of feedbacks by types. Therefore breadcrumbs are the same for all.

As to 'new feedbacks' and 'feedback with reply' notifications on the login page I am at a total loss. I am unsure of their purpose or intent. Who gets them and who has access

**Comment by SteveBiggs** [comment] 2018-10-29 17:14
I am unable to test this on test3 because there are no message notifications showing on the login page. 

On production I see this:
![image](https://user-images.githubusercontent.com/25303607/47667276-7e4b1b80-db9d-11e8-8b0f-6529eb0e4ed0.png)
On test3 I see this:
![image](https://user-images.githubusercontent.com/25303607/47667336-9c188080-db9d-11e8-9617-b62866343276.png)

On production I selected one of the 4 new feedbacks and tried to reply but it gives the red error.

**Comment by SteveBiggs** [comment] 2018-10-29 17:17
For the breadcumbs issue, I select one of the 4 new feedbacks, click on SH:
![image](https://user-images.githubusercontent.com/25303607/47667581-41cbef80-db9e-11e8-8178-8388bb87e737.png)
then click on Feedbacks:
![image](https://user-images.githubusercontent.com/25303607/47667617-5ad4a080-db9e-11e8-94f3-e3d955f910f6.png)
then get a list of ALL feedbacks from everyone.

**Comment by Captainkirkdawson** [comment] 2018-10-29 20:27
Thank you for the explanation. 
First question and most important. Do you and others want the feedback and contact notifications integrated into the message display system at login. Currently the changes made in #1526 and #1629 do NOT do that. I was unaware that it was happening or needed.
Second question. Do you and others want the feedback and contact reply notifications integrated into the message display system at login. Currently the changes made in #1526 and #1629 do NOT do that. I was unaware that it was happening or needed.

**Comment by Captainkirkdawson** [comment] 2018-10-29 20:40
The breadcrumbs issue should be resolved by the code in #1629

**Comment by SteveBiggs** [comment] 2018-10-29 20:50
My personal answer is NO to both questions. If I want to look at my contact messages, I would simply select Contacts. However, it could be useful to have a button to allow me to view any Feedbacks I have raised that are still active.

**Comment by Captainkirkdawson** [comment] 2018-10-29 20:57
OK I will not attempt any integration.
Sorry but I do not understand the comment
However, it could be useful to have a button to allow me to view any Feedbacks I have raised that are still active.
Could you expand on this?
Does the Active Feedback by Userid not give you this?

**Comment by SteveBiggs** [comment] 2018-10-29 21:13
I mean feedbacks raised by me as a member not viewing Feedbacks as Sys Admin.

**Comment by Captainkirkdawson** [comment] 2018-10-29 21:16
The red crash you are getting here is an interesting one. It is by caused by attempting to attach an image that is meaningless. In this case it is "screenshot" : "_old_", and has no location. How it got there is beyond me.
A typical image is  "screenshot" : "Capture.JPG", and has a location  "screenshot_location" : "uploads/feedback/screenshot/5b5d7f42f493fd75515a56a1/Capture.JPG",
Story #1630 proposes to check and avoid this sort of thing happening in the future

**Comment by Captainkirkdawson** [comment] 2018-10-29 21:18
Could you raise a story for the member requirement to list feedbacks they have submitted.

**Comment by SteveBiggs** [comment] 2018-10-29 21:35
Have raised #1633

**Comment by Captainkirkdawson** [comment] 2018-10-30 14:36
Will add a validity test on the attachment location

**Comment by Captainkirkdawson** [comment] 2018-10-30 17:05
trap added to ensure valid attachment and deployed to test3

**Closed as completed** 2018-11-08 22:44 UTC
Labels: Communication, Ready for Deployment, P18
