### ISSUE TITLE
how to correct witnesses ? (JulieHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#296] opened 2015-07-21 09:43 UTC
Issue reported by **JulieHarold** at 2015-07-21 09:43:54 UTC
Time: 2015-07-21T09:42:35+00:00
Session ID: 5b77307c3c7c5c4c0b754a9a30af7dfc
Problem Page URL: [/freereg1_csv_entries/5463a37de9379010fcb7e053/edit](/freereg1_csv_entries/5463a37de9379010fcb7e053/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries/5463a37de9379010fcb7e053](http://freereg2.freereg.org.uk/freereg1_csv_entries/5463a37de9379010fcb7e053)
Reported Issue:
I have a correction the witness information - but I can't see it on the details and so can't edit it.      

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment] 2015-07-21 16:17
Julie

Log in to T2 region.

then double click on your second link here.

that takes you to one of your own Full Records details so you can work out from that how to get to the one your want.

practice it in T3 first!

http://test3.freereg.org.uk/refinery/login

sherlock21

**Comment by Captainkirkdawson** [comment] 2015-07-26 23:32
Duplicate of 301

**Closed as completed** 2015-07-26 23:33 UTC
