### ISSUE TITLE
Ways for Coords to see progression of issues (was Suggestion for more useful data - problem logging) (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#586] opened 2015-11-03 15:07 UTC
Issue reported by **MikeNL** at 2015-11-03 15:07:15 UTC
Time: 2015-11-03T15:00:32+00:00
Session ID: 0e326d1ebcfe846e90194e15ff29a524
Problem Page URL: [/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-11-03+15%3A00%3A22+UTC&session_id=0e326d1ebcfe846e90194e15ff29a524&user_id=MikeNL&problem_page_url=%2Ffreereg1_csv_files%2F54639006e9379010fc4fba59%2Fedit&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Ffreereg1_csv_files%2F54639006e9379010fc4fba59&feedback_type=issue](/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-11-03+15%3A00%3A22+UTC&session_id=0e326d1ebcfe846e90194e15ff29a524&user_id=MikeNL&problem_page_url=%2Ffreereg1_csv_files%2F54639006e9379010fc4fba59%2Fedit&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Ffreereg1_csv_files%2F54639006e9379010fc4fba59&feedback_type=issue)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/54639006e9379010fc4fba59/edit](http://freereg2.freereg.org.uk/freereg1_csv_files/54639006e9379010fc4fba59/edit)
Reported Issue:
I think that it would be useful that, when a Problem Report is raised, it is allocated a number (it probably is raised within FR) that is notified to the submitter, possibly in an email that contains the details of the Problem Report and the number.

In this way, a submitter can see what his/her Problem Reports are and this could be used to ask about the status of the problem and, ultimately when there is an answer to the Problem Report, be notified that the problem has been fixed.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment] 2015-11-10 13:53
Sean and I are discussing ways that co-ords can get to see the current status of an issue/story

**Comment by Captainkirkdawson** [comment] 2015-12-17 05:23
Most of these aspects were addressed #605. The only thing not addressed were access to progress and individual notification.

**Comment by PatReynolds** [comment] 2015-12-17 10:07
Tried to change title to reflect this a couple of days ago but obviously
did not work. Will have another attempt when back in office.

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by PatReynolds** [comment] 2016-04-27 17:00
Since anyone can see the waffle board ... why don't we simply tell coords how it works and suggest they look at it?

**Comment by Captainkirkdawson** [comment] 2016-04-27 17:57
Might its volume and complexity "frighten" them? It does me!

**Comment by Sherlock21** [comment] 2016-04-27 18:00
surely a CC will not want to see ALL issues which are ongoing? Rather perhaps a selected few of their own County? or may be if they know a particular number,t hen to find the score on that one?
Has anyone asked one of the CC's Exactly what they want?

I agree with Kirk - being presented with 100% of the open ones is surely NOT whats needed.

**Comment by Captainkirkdawson** [comment] 2016-04-27 19:16
I suspect we know what they want.

What is happening on their issues.

And that is not easy to do without human intervention and system
augmentation.

I would not want to ask because then we build up the expectation of an
early response and I suspect that will not be the case.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment] 2016-09-07 10:57
Now resolved by Communications Coordinator being intermediary?

**Comment by Captainkirkdawson** [comment] 2016-09-07 13:21
Not unless that person is monitoring and providing feedback on issues

**Comment by ghost** [comment] 2016-09-07 14:02
I tell them if this is already in progress or that I have converted to
issue. I should add I also let them know if it wont be added for whatever
reason I am given.

I do let them know that if I have converted to issue, I am unable to tell
them if the issue will be accepted, or if accepted when it would be
implemented. ​

I do not think giving people updates on where their issue is in progress is
a good idea. If we give them a timeframe and it is not met, they go
bananas.

If it can be built into the programme to be an automated function, great.
Otherwise, I think what we currently do is enough

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by ghost** [comment] 2016-09-07 14:41
​Sorry I forgot to add that although I don't think it is a good idea to
give progress updates, obviously if the majority feels this would be
constructive then we will do it.

But if it is decided to do this, there need to be crystal clear guidelines
put forth. Basically I don't want updates to turn into a free for all, with
Coords demanding continual updates or modifications and such.

If we can update them simply to say that their issue will be implemented in
update X, or that the issue was closed, that may not be too bad to handle.
But I do think they need to be made to understand that we are updating them
and that's it.

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by Captainkirkdawson** [comment] 2016-09-07 17:01
I am personally happy with your current response on receipt. Only need is then to feedback on completion

**Comment by edickens** [comment] 2016-09-07 17:20
Hi Sandra,

What do you do if Kirk or anyone else puts a reply back into the Story?  
They are usually answering the senders query.  Do you pass this on?  If 
not, I don't think that they see it.

Regards,

Eric

---

Eric J Dickens
FreeREG Chairman

**Comment by ghost** [comment] 2016-09-07 20:42
Hi Eric

All that is currently done is that I first check the waffleboard to see if
the issue is in place. If not, I will usually convert it to an issue. I
will sometimes email Kirk to ask his guidance if I am unsure of anything.​

I will email the contact to let them know what is happening. If I convert
to issue. I let them know I have done this, but I cannot give them a
timeframe as to when or if their suggestions will be implemented.

If I am awaiting further information, I will let them know, and then will
come back to them and let them know at that point what will be happening at
that point. I would also email them if I am told what they are asking
cannot be done.

I was not given a specific framework of how to answer feedback. If they had
a particular issue with the website, such as recently Doreen had a problem
with not being able to use the List records breadcrumb, I would usually
email Kirk to see what needed to be done, if anything. And Kirk, that issue
resolved itself.

Otherwise once I convert to issue or give them another answer, I do not go
any further with it presently.

That said, if they need an email once their suggestion has been implemented
or completed, how would you like to proceed with that. Can I assume that if
the story number is closed, it is completed? If this is the case, I suppose
we can set up something to flag this up and then send out a standard email
to say all done.

Just point me in the right direction, and Ilush and I can figure out a set
up.

Sandra

​

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by edickens** [comment] 2016-09-07 22:17
Hi Sandra,

Fine all the way and to answer your last paragraph.  Emails are sent out 
when a Story is closed and perhaps you need a copy.

Any other improvements I'll leave to your suggestion or to those who are 
defining the communications system.

Regards,

Eric

---

Eric J Dickens
FreeREG Chairman

**Comment by ghost** [comment] 2016-09-08 09:22
Hi all

I do get emails that say X story is closed. But I did not realise that they
basically meant that the story was complete/implemented.

So I would propose that after initial reply is made to the contact by
myself or Ilush, we will then send emails to let them know the issue has
been closed.

Would a simple email just stating something like ' just to let you know
your feedback of X date has been closed. ' suffice? Any suggestions as to
what should/should not be included would be most helpful.

Will then need to set a date to commence this. I would like you all to
review the templates I put together for our responses before we implement
them.

Sandra

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by edickens** [comment] 2016-09-08 11:51
Hi Sandra,

Rather than "...closed" I would use ".... processed."  Closed gave me 
the impression that it was rejected and shut off.  Whereas Processed can 
be interpreted any way you like, either accepted, rejected or just 
looked at and discarded, but something was done..

**Comment by ghost** [comment] 2016-09-08 12:17
For your review:

1st contact when feedback converted to issue:

Dear XXXXX

Thank you for your feedback, it is greatly appreciated.

I can confirm this has been added as an issue and our website team will
review your feedback and take your points into consideration.

You will be contacted again when the issue has been processed.

Kind regards

Sandra

After issue has been closed:

Dear XXXXX

This is to confirm that your feedback has now been processed.

Thank you again for taking the time to offer your feedback.

Kind regards

Sandra

Anything else will be dealt with as and when needed, such as when the
feedback already is an issue. I would let them know this was already in the
system.

Any thoughts or suggestions for change will be appreciated. I will
implement this new structure today, as I have just converted feedback from
Kyran into an issue.

Sandra

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by Captainkirkdawson** [comment] 2016-09-08 13:06
If you feel you wish to add something more you can open the close link message, There will normally be a message saying what was done

**Comment by helhyde** [comment] 2016-09-08 13:39
Maybe explain that adding as an issue means that it is being treated as a
bug / been allocated to the current or future development phase, and will
be considered for action as part of that phase.

But other than that these look great. Thank you!

**Comment by PatReynolds** [comment] 2016-10-13 09:10
Can this now be closed?

**Closed as completed** 2016-10-13 09:22 UTC
Labels: Communication
