### ISSUE TITLE
Add ability to search multi- name SURNAMES please.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#219] opened 2015-04-25 14:29 UTC
Where a Register shows the Surname as being more than one clear surname, it must be Transcribed as written - so putting all but the last word in the first name field is wrong. The whole set must be written as Surname (TWYS). So it needs to be searchable from any of the elements - exactly like we handle multiple first names.

**Comment by benwbrum** [comment] 2015-04-25 15:32
I'd like this considered for 2.1.4.

**Comment by dougkdev** [comment] 2015-11-03 22:31
I have this working on my dev machine.  Last names are properly separated
on spaces and hyphens, and the most common surname stop-words ("de", "van",
etc.) do not have an extra search name generated for them apart from the
full surname.

Existing database entries will not benefit from this feature until
search_records are regenerated in the database.  Like the wildcard work, I
think we want this in a separate branch so as not to interfere with current
high-priority activity on master and then it can then be merged when
convenient.  Do we want each of these improvements in their own branch, or
do we want a single branch that all of the search engine improvements are
merged into?

note: #40 was marked as a duplicate of this, with some additional
information documented in it such as mentioning stop-words.

**Comment by benwbrum** [comment] 2015-11-03 22:47
I would be happy to see this in the wildcard branch, since neither future will break on the existing database.

**Comment by dougkdev** [comment] 2015-11-03 23:46
Sounds good. I added the change to the wildcard branch.

**Closed as completed** 2015-12-21 01:52 UTC
