### ISSUE TITLE
116095805 Website Problem (Claire Reilly)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1126] opened 2018-09-05 20:05 UTC
Issue reported by **Claire Reilly** at 2018-09-05 16:50:05 UTC
Time: 2018-09-05T16:49:16+00:00
Session ID: 3acb41a3ae513f5b4e708af7889599d8
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
 Please can you tell me if there is a problem with the FreeREG website at the moment?
I've been using it today and yesterday. Often (about half the time) when I do a search I'm taken straight back to the search page and all of the search fields have been emptied. 
I would expect the search results to be shown or the notice to say there are no results (which is still being shown some of the time as expected).    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5b90093df493fd515211b983/_old_)

**Comment by SteveBiggs** [comment] 2018-09-05 20:07
It's still happening ....

**Comment by Captainkirkdawson** [comment] 2018-09-06 00:58
Sorry but insufficient information to even start to research

**Comment by PatReynolds** [comment] 2018-09-06 08:52
The problem is that I fill in a search query, and hit 'search'.  Instead of going to the results page, the search page is refreshed (all data I entered is gone).  It's intermittent.  I just tried and it works fine - I will record what I was searching for and time of search when it happens again.

**Comment by SteveBiggs** [comment] 2018-09-06 08:59
Yes, the problem is that it's not reproducible at will - it appears random which I know makes it hard to investigate (I get these kinds of issues in my day job!), but there is a problem.

**Comment by edickens** [comment] 2018-09-06 09:16
What are you trying to search for when it happens?  Are you selecting any options?  I've tried all sorts of combinations with no problems.
It sounds like the "New search" button is being activated.

**Comment by SteveBiggs** [comment] 2018-09-14 11:22
I've now received several reports of this happening and will post the details I've received.

**Comment by SteveBiggs** [comment] 2018-09-14 11:37
From Anne Sherman:

Search at 16:20 on 11th Sep - 

Search all types of record.
Surname Dosser
Date range 1750-1860,
East Yorkshire - Great Driffield.
Ticked witnesses and nearby places. - back to blank search screen

Same search but untick nearby places and it shows 2 results. Untick witness but tick nearby places - blank search screen or 44 results (2 different results as I kept playing around with unticking boxes)

I have just tried it again – and the issue did not occur – 44 results every time except when I unticked nearby places when it was 2.  The only difference is that this time the page loaded much quicker (almost instant), so perhaps it is a load speed issue and it only occurs when the site is busy.   That could account for why it failed, then found 44 results and then a few minutes later is failed again.

**Comment by SteveBiggs** [comment] 2018-09-14 11:40
From Ian Stimson:

Search at 10:23 on 12th Sep -

When I enter surname driver, 1720 to 1750, west riding yorks, kildwick, search, the search starts and after about 2 seconds switches back to an empty data input page. after about six attempts I eventually got the search (about 8 lines of data)

**Comment by SteveBiggs** [comment] 2018-09-14 11:42
From Lesley Bowman:

Search around 16:15 on 13th Sep (awaiting search details)

**Comment by Sherlock21** [comment] 2018-09-14 13:25
I had similar experience about week ago

I raised a report at the time. - don't remember the number. .

**Comment by SteveBiggs** [comment] 2018-09-23 12:41
@Sherlock21 a change was made last night that we believe has fixed the search problem. Please let me know if you see it again.

**Comment by SteveBiggs** [comment] 2018-09-24 17:56
Suggest to close this.

**Closed as completed** 2018-09-26 15:35 UTC
Labels: needs info
