### ISSUE TITLE
52312189 The word information does not show on the screen as column not wide enough(Tim)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#791] opened 2016-08-28 15:24 UTC
Issue reported by **Tim37** at 2016-08-28 11:09:49 UTC
Time: 2016-08-28T11:05:21+00:00
Session ID: 1570f2c099ffc58d4eafe8f483148fce
Problem Page URL: [/freereg1_csv_files/my_own?](/freereg1_csv_files/my_own?)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
When searching the county lists - the years are in monetary format ie: 1,650 - 1,880 & it just says first & last, not first yr & last yr. The word information does not show on the screen as column not wide enough !!!!
==Copy from table==
Place Information   Changed Information Records Information First Information   Last Information
Abbotsford  25 Nov 2014  
Aldingbourne    12 Mar 2016 3,398   1,557   1,876
Amberley    13 Jan 2016 6,545   1,559   1,887
Angmering   27 Aug 2016 4,195   1,563   1,768    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2016-08-28 21:34
The numeric display is fixed but do not understand the comment about information, This is only displayed if the icon is not displayed. Would need to know devise and browser being used

**Comment by Sherlock21** [comment] 2016-09-03 13:35
I suspect that he is looking at the Coverage page of What Records We Have, (for Sussex  in his case.)
The full screen view on my iMac does not show the text: YEAR in both the From and To field headers. ( and my screen is not width restricted)

But I don't see commas in the year values that Tim says - so that must be a different issue with his apparatus)

**Comment by Captainkirkdawson** [comment] 2016-09-03 13:52
Thats because that aspect was fixed as noted.

Do not understand his comment about information going off the screen

**Comment by PatReynolds** [comment] 2016-09-05 08:05
Might be a problem if user is using a large screen and a laptop and/or
large text?

**Comment by Captainkirkdawson** [comment] 2016-09-05 13:58
The point is that the problem is not specified in a manner that a developer can investigate.

Need to know the browser being used, the page being displayed and what information is going off the screen

We could spend weeks speculating and never see the issue

**Comment by edickens** [comment] 2016-10-28 08:05
Has this been fixed?  Attached is the report in question.  It is 
![capture](https://cloud.githubusercontent.com/assets/8876165/19799241/740ef9fc-9ced-11e6-8413-e87ce895658b.JPG)
SSX.

If not, what am I suppose to do?  Am I supposed to contact the sender Tim37 or what?

**Comment by Captainkirkdawson** [comment] 2016-10-28 14:10
Nothing has been done about the story as described in its title
"The word information does not show on the screen as column not wide enough"
I do not understand the complaint. What word "Information" there isn't one unless the icon does not display and it is displaying so what are we supposed to do.
Does user still have an issue????

**Comment by edickens** [comment] 2016-10-28 14:36
No idea on this.  The word "information" appears a number of times in the headings, but never a problem for me.  I think it must be a smartphone not in landscape.  Suggest close this story.
BUT - PS - Why is the first place Abbotsford (SSX) there with no numbers?

**Comment by Captainkirkdawson** [comment] 2016-10-28 14:45
The word information should only appear if the system does not find the icon to display. If is happening then there is likely something wrong with the css being used by the browser on that page

**Comment by Sherlock21** [comment] 2016-10-28 15:04
There is no issue on my iMac.

so I would not object if you closed it.

**Comment by PatReynolds** [comment] 2016-10-30 10:16
Is the person using the word 'information' to mean 'detail'?  If the original story is edited to say 'detail' rather than 'information', is it still a story?

**Comment by Captainkirkdawson** [comment] 2016-10-30 14:21
Possibly. Since we have no real information relating to what the user did/did not see we have no way of knowing.
Speculation will waste resources..
Given that the page is being re-engineered for accessibility it is suggested we c;lose unless someone gets more information from the user.

**Comment by edickens** [comment] 2016-10-30 14:46
Close it.  E

**Closed as completed** 2016-11-16 15:49 UTC
Labels: enhancement
