### ISSUE TITLE
Detail Column in Results Page (Kyran)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#266] opened 2015-06-23 02:00 UTC
Issue reported by **Kyran** at 2015-06-23 02:00:02 UTC
Time: 2015-06-23T01:46:09+00:00
Session ID: 3108cd0521e50d4d49cd1de76799b6b7
Problem Page URL: [/search_queries/5588b84df493fd76f9000020](/search_queries/5588b84df493fd76f9000020)
Previous Page URL: [http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-06-23+01%3A37%3A24+UTC&session_id=3108cd0521e50d4d49cd1de76799b6b7&user_id=Kyran&problem_page_url=%2Fsearch_queries%2F5588b84df493fd76f9000020&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fsearch_queries%2Fnew%3Fsearch_id%3D5588b825f493fd76f900001a&feedback_type=issue](http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-06-23+01%3A37%3A24+UTC&session_id=3108cd0521e50d4d49cd1de76799b6b7&user_id=Kyran&problem_page_url=%2Fsearch_queries%2F5588b84df493fd76f9000020&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fsearch_queries%2Fnew%3Fsearch_id%3D5588b825f493fd76f900001a&feedback_type=issue)
Reported Issue:
Detail Column in results page is far right, and inaccessible for normal usage.
The page starts to show the Detail column, then overlays the page without that column (except if you go way down to the bottom of the page, you see a scroll bar to push the page over to view the Detail column.
In reality, searching such a page is impossible.  For each name to investigate, one has to highlight the row, go down to the bottom and scroll over, then go back up to the highlighted marker and click the Detail link.
The problem seems to be one or two entries in the Location column have too much text and it stretches out the width of that column too wide to include Details on the same screen,
That long description needs to be broken up somehow, so the entire result rows show up at one time.
Or the Location field needs to be limited and word-wrapped (when using the dates 1700-1800 and 1600-1700, it all worked fine - no long names!).
I searched 
surname: Parfrey / First year: 1800 / Last year: 1900 / County: Somerset / Record type: Baptism / Soundex: On.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2015-07-26 23:35
Duplicate of 522

**Closed as completed** 2015-07-26 23:35 UTC
