### ISSUE TITLE
Updating of statisitics after editing a record (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#349] opened 2015-08-14 14:59 UTC
Issue reported by **REGManager** at 2015-08-14 14:59:26 UTC
Time: 2015-08-14T14:54:36+00:00
Session ID: 4c13da9814268b0cdcd1155388886bf6
Problem Page URL: [/freereg1_csv_files/5463cb8de9379010fc6a7a40](/freereg1_csv_files/5463cb8de9379010fc6a7a40)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files?page=](http://freereg2.freereg.org.uk/freereg1_csv_files?page=)
Reported Issue:
I've just noticed that although the decade analysis is updated, the first and last year is not.  I changed 1107 to 1707, which is why the first entry in decade is now zero but the first year has not changed.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1439564366-79894-1168/Capture.JPG)

**Comment by Captainkirkdawson** [comment] 2015-09-03 02:50
Duplicate of #368

**Closed as completed** 2015-09-03 02:50 UTC
Labels: duplicate
