### ISSUE TITLE
Link from search detail through to creating institution (e.g. Church) and repository

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#805] opened 2016-09-18 08:18 UTC
The Transcriptions link on the search page takes you to a county, its places, churches and registers. At the county level you get information about the coordinator and county. At the Place level you receive information about the place. At the church level you get information about the church including links to the church (if entered). At the register level you get information about the register.

On a search you get access to the details of a specific transcription. There is a link which takes you to the summary Place information for the place in which the record was located, which is the same as the place level display in transcriptions BUT there are no links to the county, church  or register levels.

**Comment by Captainkirkdawson** [comment] 2016-09-19 20:32
#439 is relevant

**Comment by Captainkirkdawson** [comment] 2018-02-17 18:01
This is duplicate of #1306

**Closed as completed by Captainkirkdawson** 2018-02-17 18:01 UTC
