### ISSUE TITLE
time out while replacing a batch (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#99] opened 2014-11-26 19:39 UTC
Issue reported by **ericb** at 2014-11-26 19:39:45 UTC
Time: 2014-11-26T19:33:52+00:00
Session ID: 654c78f5ddf78cf61475a6fe4934a54f
Problem Page URL: [/feedbacks/new?utf8=%E2%9C%93&feedback_time=2014-11-26+19%3A31%3A14+UTC&session_id=654c78f5ddf78cf61475a6fe4934a54f&user_id=ericb&problem_page_url=%2Fcsvfiles%2F5463cd9be9379010fc74456d%2Fedit%3F&previous_page_url=http%3A%2F%2Ftest2.freereg.org.uk%2Ffreereg1_csv_files%2Fselection%3Foption%3DList%2520by%2520Filename&feedback_type=issue](/feedbacks/new?utf8=%E2%9C%93&feedback_time=2014-11-26+19%3A31%3A14+UTC&session_id=654c78f5ddf78cf61475a6fe4934a54f&user_id=ericb&problem_page_url=%2Fcsvfiles%2F5463cd9be9379010fc74456d%2Fedit%3F&previous_page_url=http%3A%2F%2Ftest2.freereg.org.uk%2Ffreereg1_csv_files%2Fselection%3Foption%3DList%2520by%2520Filename&feedback_type=issue)
Previous Page URL: [http://test2.freereg.org.uk/csvfiles/5463cd9be9379010fc74456d/edit?](http://test2.freereg.org.uk/csvfiles/5463cd9be9379010fc74456d/edit?)
Reported Issue:
I had just replaced one batch OK.
Then started to do second  Batch. WRYAVTBA2.csv

After a while,i got a Gateway timeout msg

Where has job got to please?    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1417030785-23212-7010/Screen_shot_2014-11-26_at_19.33.18.png)

**Comment by Captainkirkdawson** [comment] 2014-11-26 20:22
Started a build at 2014-11-26 16:41:21 +0000with options of recreate with
create_search_records a base directory at /raid-test/freereg2/users and a
file ericb/SOMTSTBA4.csv
1        files selected for processing
ericb   SOMTSTBA4.csv
ericb   SOMTSTBA4.csv   processed  29 data lines
Created  31 entries at an average time of 334.02534223333333ms per record
at 2014-11-26 16:41:31 +0000
 File SOMTSTBA4.csv uploaded successfully at 2014-11-26 16:41:17 +0000 for
ericb
Started a build at 2014-11-26 16:55:15 +0000with options of recreate with
create_search_records a base directory at /raid-test/freereg2/users and a
file ericb/SOMTSTBA4.csv
1        files selected for processing
ericb   SOMTSTBA4.csv
ericb   SOMTSTBA4.csv   processed  29 data lines
Created  31 entries at an average time of 30.556482166666665ms per record
at 2014-11-26 16:55:16 +0000
 File SOMTSTBA4.csv uploaded successfully at 2014-11-26 16:55:11 +0000 for
ericb
Started a build at 2014-11-26 16:59:36 +0000with options of recreate with
create_search_records a base directory at /raid-test/freereg2/users and a
file ericb/SOMTSTBA4.csv
1        files selected for processing
ericb   SOMTSTBA4.csv
ericb   SOMTSTBA4.csv   processed  29 data lines
Created  31 entries at an average time of 39.33725223333333ms per record at
2014-11-26 16:59:37 +0000
 File SOMTSTBA4.csv uploaded successfully at 2014-11-26 16:59:32 +0000 for
ericb
Started a build at 2014-11-26 17:04:30 +0000with options of recreate with
create_search_records a base directory at /raid-test/freereg2/users and a
file ericb/SOMTSTBA9.csv
1        files selected for processing
ericb   SOMTSTBA9.csv
ericb   SOMTSTBA9.csv   processed  29 data lines
Created  31 entries at an average time of 19.4040457ms per record at
2014-11-26 17:04:31 +0000
 File SOMTSTBA9.csv uploaded successfully at 2014-11-26 17:04:27 +0000 for
ericb
 File WRYAVTBA1.csv uploaded successfully at 2014-11-26 19:30:40 +0000 for
ericb
Started a build at 2014-11-26 19:31:08 +0000with options of recreate with
create_search_records a base directory at /raid-test/freereg2/users and a
file ericb/WRYAVTBA1.csv
1        files selected for processing
ericb   WRYAVTBA1.csv
ericb   WRYAVTBA1.csv   processed  465 data lines
Created  467 entries at an average time of 14.360929693133047ms per record
at 2014-11-26 19:31:15 +0000
 File WRYAVTBA2.csv uploaded successfully at 2014-11-26 19:33:28 +0000 for
ericb
 File WRYAVTBA3.csv uploaded successfully at 2014-11-26 19:42:10 +0000 for
ericb

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment] 2014-11-26 21:13
Thanks for this K

So how doe they move on from the uploaded condition to the Processing and ultimately  completed please.?

At 21:12 the BA2 andBA3 are not showing as present in ericb Batches.

EricB

**Comment by Captainkirkdawson** [comment] 2014-11-26 22:04
At this stage only by a new upload. I had wanted to develop that extra
functionality

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment] 2015-01-01 23:56
Duplicate of safari time out

**Closed as completed** 2015-01-01 23:55 UTC
Labels: duplicate
