### ISSUE TITLE
Some files appear to be missing (chriselliott)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#512] opened 2015-10-21 14:06 UTC
Issue reported by **chriselliott** at 2015-10-21 14:06:57 UTC
Time: 2015-10-21T14:00:32+00:00
Session ID: 0c2eca1b7e9f98d2d2c8284bb57f635c
Problem Page URL: [/freereg1_csv_files/selection?option=List%20by%20Filename](/freereg1_csv_files/selection?option=List%20by%20Filename)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/my_own?](http://www.freereg.org.uk/freereg1_csv_files/my_own?)
Reported Issue:
UserID   chriselliott

When I access List by Filename, the list generated stops at Houghton le Spring in an alphabetical list but I have many more files that are not being displayed.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2015-10-21 15:01
Duplicate of 509 and 514

**Closed as completed** 2015-10-21 15:01 UTC
