### ISSUE TITLE
Review Contact Management Process

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#209] opened 2015-04-18 12:45 UTC
Issue reported by **Martin Stockham** at 2015-04-18 12:45:46 UTC
Time: 2015-04-18T12:27:50+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts](http://freereg2.freereg.org.uk/contacts)
Reported Issue:
I am attaching a screen shot of a current record from Norton Malreward - I cannot tell if reporting an error automatically identifies the record or not. I have site of a photocopy of the original parish entry and I believe the correct entry should be:
No.51 (possibly 57) William Thomas of Bridgewater..County of Somerset Batchelor and Hannah Stockham of Norton Malreward..said County..Spinster was married by licence in this church the Sixth day of November One Thousand Eighteen Hundred and Six.  I am sure this is STOCKHAM and that the date is 1806 not 1808. Also - I believe one of the witnesses is William Taylor.      

![Screenshot](http://test-cluster.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1429361146-56046-2240/Screen_Shot_2015-04-18_at_13.30.02.jpg)

**Comment by benlaurie** [comment] 2015-04-18 12:52
On 18 April 2015 at 14:45, FreeUKGenIssues notifications@github.com wrote:

> Issue reported by _Martin Stockham_ at 2015-04-18 12:45:46 UTC
> Time: 2015-04-18T12:27:50+00:00
> Session ID:
> Problem Page URL:
> Previous Page URL: http://freereg2.freereg.org.uk/contacts
> Reported Issue:
> I am attaching a screen shot of a current record from Norton Malreward - I
> cannot tell if reporting an error automatically identifies the record or
> not.

It doesn't, it seems, but would be a good idea!

**Comment by edickens** [comment] 2015-04-18 12:59
```
And the screenshot just gives "Not found".

Also, we do not have the email address of the sender, so cannot send
a reply asking for more detail.
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 18/04/2015 13:52, Ben Laurie wrote:

```
On 18 April 2015 at 14:45, FreeUKGenIssues
  <notifications@github.com> wrote:

  > Issue reported by *Martin Stockham* at 2015-04-18 12:45:46
  UTC
  > Time: 2015-04-18T12:27:50+00:00
  > Session ID:
  > Problem Page URL:
  > Previous Page URL: http://freereg2.freereg.org.uk/contacts
  > Reported Issue:
  > I am attaching a screen shot of a current record from Norton
  Malreward - I
  > cannot tell if reporting an error automatically identifies
  the record or
  > not.
  >

  It doesn't, it seems, but would be a good idea!


  > I have site of a photocopy of the original parish entry and I
  believe the
  > correct entry should be:
  > No.51 (possibly 57) William Thomas of Bridgewater..County of
  Somerset
  > Batchelor and Hannah Stockham of Norton Malreward..said
  County..Spinster
  > was married by licence in this church the Sixth day of
  November One
  > Thousand Eighteen Hundred and Six. I am sure this is STOCKHAM
  and that the
  > date is 1806 not 1808. Also - I believe one of the witnesses
  is William
  > Taylor.
  >
  > [image: Screenshot]
  >
```

https://camo.githubusercontent.com/8aa804b24dcba6288b2c37dcac4f6265d98da70d/687474703a2f2f746573742d636c75737465722e667265657265672e6f72672e756b2f686f6d652f6170616368652f686f7374732f66726565726567322f70726f64756374696f6e2f746d702f63617272696572776176652f313432393336313134362d35363034362d323234302f53637265656e5f53686f745f323031352d30342d31385f61745f31332e33302e30322e6a7067
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
      https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/209.
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by benwbrum** [comment] 2015-04-18 14:32
Looks like we need to review and revise the problem report button.  The
original design of the problem report was to include referrer URLs in the
problem.  (cf http://www13.freereg.org.uk/feedbacks/552e80f8f493fd77dc000897
)

To my surprise, the feedback reports on the production site don't quite
match the issues pushed to github.

Ben

**Comment by Captainkirkdawson** [comment] 2015-04-19 16:17
BenL/BenB

If the user reports the data problem using the link at the top of the page where the record is being reviewed then there is a link to the specific record in question placed in the email sent to the coordinator and data manager. It can only be activated if logged into the FR2 as a member with the appropriate roles.
Also the Contact collection is reviewable by those people whose role includes access to the Contents collection. In there all contact types are stored and can be reviewed and if the contact cams from the record page it will contain an active link to that record.
Martin found this link in a subsequent submission.

**Comment by Captainkirkdawson** [comment] 2015-05-08 13:59
Duplicate of 468

**Closed as completed** 2015-05-08 14:00 UTC
Labels: duplicate
