### ISSUE TITLE
70208750 Abbreviation issue (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#943] opened 2017-03-24 22:48 UTC
Issue reported by **alsibk** at 2017-03-23 14:25:50 UTC
Time: 2017-03-23T14:14:53+00:00
Session ID: 5eae2b4fa19c6ec0701556cf00a9a7fc
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new](https://www.freereg.org.uk/manage_resources/new)
Reported Issue:
A search for Robt (transcribed as Robt.) is unsuccessful unless name soundex is selected. This is not made clear in the help, where it is stated----

“Abbreviations and Latin versions of the forename (first name) will be included automatically”
http://www13.freereg.org.uk/uploads/feedback/screenshot/58d3daeef493fd7544d388f2/Robt..jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58d3daeef493fd7544d388f2/Robt..jpg)

**Comment by suffolkroots** [comment] 2017-03-25 07:09
Clearer screenshot--
![robt 2](https://cloud.githubusercontent.com/assets/10379655/24320267/bd3ab732-1129-11e7-8904-7d4de89712be.jpg)

**Comment by benwbrum** [comment] 2017-03-25 13:48
The period is what's causing the problem here.

If your search term includes an abbreviation "Wm", we will do an exact
match on records transcribed with that abbreviation, so "Wm" will be
returned, but "William" won't.

If your search term includes a full name which is frequently abbreviated
"William", we will do a search on records transcribed with the full name or
abbreviation, so "Wm" will be returned as well as "William".  (I suspect
"Wm." will also be returned, but I'll have to test it.)

The search for "Robt" is doing an exact search, and since "Robt" is not
"Robt.", it's failing.

**Comment by suffolkroots** [comment] 2017-03-25 13:56
This suggests that the help info---

"Abbreviations and latin versions of the forename (first name) will be included automatically"

might usefully be amended.

**Comment by FreeUKGenIssues** [comment] 2017-03-25 14:47
I agree -- they are included in the search results automatically if someone
searches for a full name.  If they search for an abbreviation, it'll do an
exact match only.  Maybe we should illustrate with an example?

**Comment by Captainkirkdawson** [comment] 2017-03-25 15:20
There are 2 points here.
1) The abbreviation is a one one search system. ie. Robert looks for all the abbreviations. A search using an abbreviation looks for an exact match of the abbreviation.
2) This record is NOT retrieved by a search for Robert. It should be. Looking at the search record in the database shows no creation of the expansion.
        "record_type" : "ba",
        "search_record_version" : "2016-10-31T00:00:00+00:00",
        "chapman_code" : "WRY",
        "line_id" : "lwilmot.WRYHAMBA.CSV.143",
        "transcript_names" : [
                {
                        "role" : "ba",
                        "type" : "primary",
                        "first_name" : "Robt.",
                        "last_name" : "STEWARD"
                }
        ],
        "freereg1_csv_entry_id" : ObjectId("556148baf493fd3934031763"),
        "search_date" : "1608-*-*",
        "place_id" : ObjectId("53cbf61feca9eb03a600b334"),
        "digest" : "fONo02Hq5grqJGVDyOfrEg==",
        "search_names" : [
                {
                        "_id" : ObjectId("5817b49fe93790eca3bb69e6"),
                        "first_name" : "robt.",
                        "last_name" : "steward",
                        "origin" : "transcript",
                        "type" : "p",
                        "role" : "ba",
                        "gender" : null
                }
        ]

**Comment by Captainkirkdawson** [comment] 2017-03-25 15:38
Looking at the entry
 "_id" : ObjectId("556148baf493fd3934031763"),
        "error_flag" : "false",
        "line_id" : "lwilmot.WRYHAMBA.CSV.143",
        "file_line_number" : 143,
        "register_entry_number" : null,
        "birth_date" : "1608",
        "baptism_date" : null,
        "year" : null,
        "person_forename" : "Robt.",
        "person_sex" : null,
        "father_forename" : null,
        "mother_forename" : null,
        "father_surname" : "STEWARD",
        "mother_surname" : null,
        "person_abode" : "Daker pasture",
        "father_occupation" : null,
        "notes" : "Born as is said 1608",
        "county" : "WRY",
        "place" : "Hampsthwaite",
        "church_name" : "St Thomas a Becket",
        "register_type" : "TR",
        "record_type" : "ba",
        "freereg1_csv_file_id" : ObjectId("556148b9f493fd393403152f"),
        "record_digest" : "m+o7TugdeY8T2FChrMl3Wg==",
        "u_at" : ISODate("2015-05-24T03:42:50.275Z"),
        "c_at" : ISODate("2015-05-24T03:42:50.275Z")

Shows that it was created on "2015-05-24T03:42:50.275Z" and never been updated.
The latter is interesting as the search record show that it was created with  "search_record_version" : "2016-10-31T00:00:00+00:00", which was when we ran a rebuild of the search_records for emendations. Clearly this record should have been updated. 

What I would ask is if Ali could update that specific record in the file (Add a space to the note field should force an update} and reload the file. This should create the appropriate search names. If it does not then we have one type of bug. If it does then we have another type of bug.

**Comment by suffolkroots** [comment] 2017-03-26 08:51
The file WRYHAMBA.CSV has been updated and re-loaded as per request.

**Comment by ghost** [comment] 2017-03-26 10:11
This morning we have had an email for a member of the public regarding this issue, the email states: 

Please add the following to the Forename Abbreviations at https://www.freereg.org.uk/emendation_rules to enable users to find their ancestors: To Abigail add Abigal To Margaret add Margarett Create an entry for Harriet and add Harriett, Harriott, and Harriot (at least; might as well add the variants with one 'r', too) To Humphrey add Humphry Create an entry for Phoebe and add to it Phebe Combine the entries for Catharine and Catherine. These are the same name, so if I search for Catherine, I should get the records of people with the name Catharine, Kathryn, Katherine, Katharine, and so forth. This is currently not the case. Soundex is practically worthless because it finds way too many hits, which cause the server to timeout and fail to return any information at all. Even when it works, it results in names which are not even close to the name being searched, because Soundex is based only on the first 3 consonants of the name. When I search for my own surname, for example, I get records for Beardmore. There's just no way those two names would ever be confused.

Might I suggest that a separate page be added dedicated to a comprehensive list of names and their variations? There was at one time a list on the old FreeREG site that could be used but would need updating of course. I would be more than happy to take this project on because I think it would be most beneficial to our researchers, not only on FR but also to assist them in research beyond our pages, as they not think to look for Catharine, Kathryn, Katherine, Katharine, Catharina, Catherine etc.

**Comment by Captainkirkdawson** [comment] 2017-03-27 16:49
This shows that we did not create an emendation record for robt.
{
        "_id" : ObjectId("58d69825f493fd65b7976c53"),
        "transcript_dates" : [
                "",
                "1608"
        ],
        "search_dates" : [
                "",
                "1608-*-*"
        ],
        "location_names" : [
                "Hampsthwaite (St Thomas a Becket)",
                " [Transcript]"
        ],
        "search_soundex" : [
                {
                        "first_name" : "R130",
                        "last_name" : "S363",
                        "type" : "p"
                }
        ],
        "record_type" : "ba",
        "search_record_version" : "2017-03-21T15:44:07+00:00",
        "chapman_code" : "WRY",
        "line_id" : "lwilmot.WRYHAMBA.CSV.143",
        "transcript_names" : [
                {
                        "role" : "ba",
                        "type" : "primary",
                        "first_name" : "Robt.",
                        "last_name" : "STEWARD"
                },
                {
                        "role" : "f",
                        "type" : "other",
                        "first_name" : "",
                        "last_name" : "STEWARD"
                },
                {
                        "role" : "m",
                        "type" : "other",
                        "first_name" : "",
                        "last_name" : "STEWARD"
                }
        ],
        "freereg1_csv_entry_id" : ObjectId("58d69825f493fd65b7976c52"),
        "search_date" : "",
        "secondary_search_date" : "1608-*-*",
        "place_id" : ObjectId("53cbf61feca9eb03a600b334"),
        "digest" : "zKC2wRBeMKa8QF8oe41BHA==",
        "u_at" : ISODate("2017-03-25T16:17:41.307Z"),
        "c_at" : ISODate("2017-03-25T16:17:41.307Z"),
        "search_names" : [
                {
                        "_id" : ObjectId("58d69825f493fd65b7976c54"),
                        "first_name" : "robt.",
                        "last_name" : "steward",
                        "origin" : "transcript",
                        "type" : "p",
                        "role" : "ba",
                        "gender" : null
                },
                {
                        "_id" : ObjectId("58d69825f493fd65b7976c55"),
                        "first_name" : "",
                        "last_name" : "steward",
                        "origin" : "transcript",
                        "type" : "f",
                        "role" : "f",
                        "gender" : "m"
                },
                {
                        "_id" : ObjectId("58d69825f493fd65b7976c56"),
                        "first_name" : "",
                        "last_name" : "steward",
                        "origin" : "transcript",
                        "type" : "f",
                        "role" : "m",
                        "gender" : "f"
                }
        ]
}

**Comment by benwbrum** [comment] 2017-03-27 18:41
The hash lookup we're using to test for names does not strip punctuation
from names.  If we revised this part of the emendor, we'd fix this problem.

**Comment by Captainkirkdawson** [comment] 2017-03-27 20:55
There is also a problem with our display of emendations in that it shows a bunch of punctuation emendations that we are not applying. eg we say that Robt. is emended when it is not; similarly we say the following for r and i don't believe we do most of the punctuation ones
https://www.freereg.org.uk/emendation_rules#r

This is spun off as #1200

**Comment by ghost** [comment] 2017-03-29 22:52
Mick highlighted another issue: Ann is not recognised as alternative for Anne.

I had a look at the page Kirk highlighted. Is this viewable by the public at large, or is this just for the programmers? 

I am curious, looking at Ann for example, how is Mary-Ann in all its different spellings/abbreviations, an abbreviation for Ann? I will admit the page does not make a lot of sense to me, and if it is publically viewable, yikes.

**Comment by richpomfret** [comment] 2017-04-03 15:27
To update the help documentation to reflect what we actually do. To then discuss with Ben re: how we might change the way our system handles these cases.

**Comment by richpomfret** [comment] 2017-06-07 16:00
Removed task 1200 as duplicate of this one.

**Comment by Captainkirkdawson** [comment] 2017-06-13 16:37
Have determined that of  40521 originals 35947 were emended and 4574 unemended.
In the process of determining weither this is a code error or if the rebuild of the emendations some months ago mal functioned.

**Comment by Captainkirkdawson** [comment] 2017-06-13 16:44
Futher analysis shows that of those that did not have an emendation for robt. they had nil creation/updated dates on the search record and that some did have correct emendations for other rules eg thom. to thomas

**Comment by Captainkirkdawson** [comment] 2017-06-13 17:11
For will. to william of 16221 originals 15625 were emended and 596 unemended.

**Comment by Captainkirkdawson** [comment] 2017-06-14 16:13
Clearly the majority of search records BUT NOT ALL are correctly emended. Will modify the detection rake to fix those that were unemended

**Comment by Captainkirkdawson** [comment] 2017-06-14 17:59
The main issue appears to be emending witness names. Witness names have no sex hence rules that apply to a specific sex are not being applied to witnesses.

**Comment by Captainkirkdawson** [comment] 2017-06-14 20:22
In addition there were other records in the database for ba , bu and ma that had not been emended.
Testing a correction rake task that uses the first_name index on search records to idenify those records that may need emending and if not emended then it applies the emendation

**Comment by Captainkirkdawson** [comment] 2017-06-14 21:58
Ran a correction for robt. and will. on the production system with no service impact.
Now analysing the total number of affected records for all emendations

**Comment by Captainkirkdawson** [comment] 2017-06-15 00:08
A total of 7621334 records examined for 2494 rules with 6127309 emended and 1494025 unemended. ie. 20 % of the records that should be emended are not.

**Comment by Captainkirkdawson** [comment] 2017-06-15 02:45
Have commenced a production update

**Comment by Captainkirkdawson** [comment] 2017-06-15 14:29
A total of 7718026 records examined for 2494 rules with 6296290 emended, 1421736 unemended and attempted to correct in 7 hrs 30 mins with minimal service impact.

**Comment by Captainkirkdawson** [comment] 2017-06-15 14:33
The original entry that started this epic is now retrieved with a search for Robert Steward
![steward](https://user-images.githubusercontent.com/2874694/27186349-4db8876a-51a5-11e7-8ced-673533a8f905.JPG)

**Comment by Captainkirkdawson** [comment] 2017-06-15 14:45
For those interested in the usage of the various abbreviations

https://docs.google.com/document/d/1dlL39dwzqre0QIlrl2foVr9SLHLXyyqhJQrcequok7g/edit

**Comment by Captainkirkdawson** [comment] 2017-06-16 14:34
The zipped error file for anyone wishing to review and make corrections is on the gdrive
https://drive.google.com/open?id=0BykgQKwJtk6fSG1YMTMyWGpXRjQ

**Closed as completed** 2017-06-21 15:44 UTC
Labels: bug, Actor: researcher

**Comment by edickens** [comment] 2017-06-22 08:52
I cannot open this file to assess the problem.  It is 573MB and Crimson Editor says I do not have enough memory.  Notepad is just a jumble.  Any thoughts?  ED

**Comment by edickens** [comment] 2017-06-22 10:04
After much fiddling I have got access to the first few records and compared them to the server.
The first looks like a genuine error:-
SOM,Ilchester,St Mary Major PR,"",09 Feb 1790,James,son of,"",Benjm,LYE,LYE,"","","",M1577-1,041
Fortunately this is on the image server and the film/image number is given and this is the original entry:-
![capture](https://user-images.githubusercontent.com/8876165/27428381-be438d88-5739-11e7-8cde-6ce459f4986e.JPG)
I think there will be a lot like this and the advice to researchers should be to omit the forename if they do not find that they are looking for.  The forename is really to just reduce a too large search after a year range produced too many results.  ED

**Comment by edickens** [comment] 2017-06-22 10:08
PS.  Usually if only one parent's name is given it is the mother, but that is BA not BU.
This can be found on FR at ChrisP.SOMILHBU5.CSV.138
ED

**Comment by edickens** [comment] 2017-06-22 10:09
PPS.  This is a good example why we need V1.5 to link transcriptions to the images.  ED

**Comment by edickens** [comment] 2017-06-22 11:48
The next us interesting, but different.

plancast1.NFKGYABA.CSV.4574

NFK,Great Yarmouth,St Nicholas PR,2126,"",22 Feb 1820,Benjm Samuel,F,Willm,Ann,PASTON,"",Yarmouth,Keelman,"",4143435,1860

Here the film and image numbers are quoted, but they are not on the image server.  I have no means of checking.  But it would appear that F instead of M has been entered.

ED

**Comment by edickens** [comment] 2017-06-25 16:28
I have checked a few of these entries in Kirk's huge report.  They do seem to be transcription errors,  although they will not affect the search.  I think that this Rake Task needs to be kept and turned into a report which can be organised by CC when we get to V2 - Extra management Actions.
