### ISSUE TITLE
Counties in the searchable list (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#183] opened 2015-03-06 08:25 UTC
Issue reported by **REGManager** at 2015-03-06 08:25:42 UTC
Time: 2015-03-06T08:09:52+00:00
Session ID: 0b4eb807b98b682370af288763f9c41a
Problem Page URL: [/counties/531a1999231040725c000053](/counties/531a1999231040725c000053)
Previous Page URL: [http://freereg2.freereg.org.uk/counties](http://freereg2.freereg.org.uk/counties)
Reported Issue:
Following on from discussion at our Sprint Review, I have thought about the counties that need to be shown to researchers on the Search Screen.
The list should be alphabetic (as in FR1), include all that we are working on including those that do not have any data.  At present there are no markers that I can enter against each county to say if we are working on them or not.  See attached list of fields.  For, example, we are not accepting data for any of the Ireland counties, nor for ENG, YKS and other more modern Chapman codes.  The list of counties seems to be set up manually and not against any County Record information.  If this is the case, then how will it get changed in the future?
May I suggest that we have two new fields in the County record - "In use" and "Accepting transcriptions".  These can then be used at various times in the website.  If the "In use" is false it will not be displayed in the Search page list of counties; the "Accepting transcriptions" will be used to validate transcriptions.
EricD    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1425630342-42451-6747/Capture.JPG)

**Comment by Sherlock21** [comment] 2015-03-06 09:32
Please cross ref this to my comments on #177 - as there is overlap between the two topics.

I agree we need to provide for simple, easy adjustment in the future, as we expand coverage.

**Comment by Captainkirkdawson** [comment] 2015-03-18 01:56
Duplicate of 177

**Closed as completed** 2015-03-22 16:39 UTC
Labels: duplicate
