### ISSUE TITLE
209222854 Website Problem (James Santos)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1442] opened 2021-08-18 16:04 UTC
Issue reported by **James Santos** at 2021-08-18 13:27:34 UTC
Time: 2021-08-18T13:01:47+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Hello

I'm a Mac use with OS Catalina and use Firefox as a web browser, which actually updated yesterday 18 Aug 2021... I always have used Firefox for many years and prefer edit to Apple's Safari... for the past week or so when wishing to use the FreeReg site via the Firefox browser, your site  allows me to enter the name(s), dates, counties and when there are results, as usual it will show a list of people who fall within my search criteria... there seems to be a technical issue, in that when I attempt click on the little blue box to open ANY of the records to see the further details, NOT a single box will open... this happens regardless of what details I try, plus this is happening right across all counties. I've tried closing the page, clearing all cookies, caches, browser history, and closing Firefox down completely, I even tried restarting my iMac several times, yet I'm still getting the same technical issue in that NONE of the blue boxes will open! Prior to sending this message I obviously/wisely decided to open Safari and and try a few searches via Safari and every time I've tried EVERY single box opens allowing me the full details which is great! However, I do not want to have to keep using to web browser's whilst do genealogical research... can you please tell me if the FreeReg site is having technical issues for Mac & Firefox users, or are you even aware that there is a technical issue for Mac users who use the Firefox web browser?  I would be sincerely grateful if someone could take a look at this technical issue and please come back to me about the problem! kind Regards... James Santos

**Comment by SteveBiggs** [comment] 2021-08-18 16:07
This is the second Mozilla Firefox user to raise this issue today and since he says it's been for the last week or so, it seems likely that something from the s/w deployment after the last Scrum may have caused the problem.

**Comment by PatReynolds** [comment] 2021-08-18 16:55
@SteveBiggs to ask users to try FreeCEN search.

**Comment by SteveBiggs** [comment] 2021-08-18 17:20
Request sent to user.

**Comment by SteveBiggs** [comment] 2021-08-21 16:07
From Doreen Olds:
"are you or any of the transcribers having problems with FreeREG & Firefox?
It was ok until there was an update. I restored my computer to an earlier date and all was ok. Then when I logged on this morning Firefox did the update again and now I can't use FreeREG at all."

**Comment by Captainkirkdawson** [comment] 2021-08-21 16:58
@SteveBiggs I have just updated Firefox to its Release of 4 days ago and on Windows there are no problems with any of our applications. I am unable to test on a Mac.
@Vino-S can you please look at this as you use that platform.

**Comment by SteveBiggs** [comment] 2021-08-21 18:27
Thanks @Captainkirkdawson , two of the reports have been Windows 7 users and the others use a Mac, so it appears to only be those platforms that have a problem with the Firefox update - Windows 10 seems to be fine.

**Comment by suffolkroots** [comment] 2021-08-22 09:05
I reported this to Steve earlier this week, need to turn off Firefox enhanced tracking (shield at left of address bar}. BMD or CEN are not affected.
Platform is Windows 10 @SteveBiggs.

**Comment by SteveBiggs** [comment] 2021-08-22 09:54
My apologies, @suffolkroots , you did send this and I forgot about it! Hopefully, this will fix it for all users.

**Comment by suffolkroots** [comment] 2021-08-22 11:24
Has to be turned off every time, so hope it's a temporary fix, looks like a FreeREG problem not Firefox.

**Comment by SteveBiggs** [comment] 2021-08-22 14:00
@suffolkroots I hope FreeREG can be made to function with enhanced tracking protection on, but in the meantime, you shouldn't have to do it every time you visit FreeREG - you can set it so that it's permanently off for a given site per this I found online:
![image](https://user-images.githubusercontent.com/25303607/130357867-700badf7-e71b-49a6-8fa0-81ffd964840a.png)

**Comment by suffolkroots** [comment] 2021-08-22 16:39
Thanks Steve, I've seen that, but it's only off until I log off, access the site again and it's back. It's a nuisance, hope it can be fixed.
(I'm not using strict blocking)

**Comment by SteveBiggs** [comment] 2021-08-22 17:11
Oh really? That's not good. I would have thought it should persist for the site once set. If CEN is fine, we should be able to sort it for REG.

**Comment by Sherlock21** [comment] 2021-08-22 17:18
There is no problem with Mac and Safari from my experience these past few days.

**Comment by SteveBiggs** [comment] 2021-08-22 17:47
Ther wouldn't be @Sherlock21, it's a FreeREG/Firefox issue.

**Comment by Vino-S** [comment] 2021-08-23 10:43
The issue appears in my system when I set Protection Mode to Strict. However, I do not have any issue with the FreeCEN even in strict mode.
![image](https://user-images.githubusercontent.com/26073943/130433615-131e5842-49c3-48be-a3ba-518b3d51acbe.png)

FreeREG: All the links are broken. The Search button is working. 
I think the problem is caused by the Advert cookies. 

One way to fix the problem is to choose the Standard Protection Mode.
![image](https://user-images.githubusercontent.com/26073943/130433771-a9b71bc2-297f-4c82-93b9-cda5afca177e.png)

**Comment by suffolkroots** [comment] 2021-08-23 11:06
FR, Test2 and Test3 all have this problem. I have my settings at Standard mode. Have to disable enhanced tracking every time.

**Comment by SteveBiggs** [comment] 2021-08-23 14:16
@Vino-S why does FreeREG handle advert cookies differently to FreeCEN?

**Comment by Vino-S** [comment] 2021-08-23 14:41
@SteveBiggs ,
In FreeCEN we use our own self generated adverts. But in FreeREG advertisements are managed by MonetizeMore.

My conclusion might be wrong, because FreeBMD also has advertisements managed by MonetizeMore but I see no issues over there in my system.

**Comment by PatReynolds** [comment] 2021-10-13 17:18
Closing issue are related issue now solved.

**Closed as completed** 2021-10-13 17:19 UTC
