### ISSUE TITLE
County is not displayed (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#411] opened 2015-09-10 10:11 UTC
Issue reported by **MikeNL** at 2015-09-10 10:11:56 UTC
Time: 2015-09-10T10:10:02+00:00
Session ID: a582c20704ef463c4eecb548ca15f90e
Problem Page URL: [/freereg1_csv_files/55f0e986f493fd6626029343/edit](/freereg1_csv_files/55f0e986f493fd6626029343/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/selection?option=List%20by%20uploaded%20date%20(descending)](http://freereg2.freereg.org.uk/freereg1_csv_files/selection?option=List%20by%20uploaded%20date%20%28descending%29)
Reported Issue:
Updating header information on a batch does not display the county name in the "where" heading.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2015-09-11 21:32
Duplicate of 381

**Closed as completed** 2015-09-11 21:32 UTC
Labels: duplicate
