### ISSUE TITLE
144608015 Notification of file uploads (Linda)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1235] opened 2019-08-02 15:04 UTC
Issue reported by **Adnil** at 2019-08-01 16:53:35 UTC
Time: 2019-08-01T16:37:32+00:00
Session ID: e5c17a607b35b142e5facc2a5f57936c
Problem Page URL: [/manage_counties/select_action?locale=en](/manage_counties/select_action?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
If I successfully upload a file for a transcriber that is no longer in my syndicate I am notified of this fact.

However if the file does not upload successfully due to an error in the file the notification goes to his current coordinator so hence I am not aware of this unless the current coordinator lets me know.

Linda Railton NRY    

![Screenshot](https://www.freereg.org.uk)

E0 U 4 S7 C6: P17

**Comment by SteveBiggs** [comment] 2019-08-04 09:36
Note that Linda is uploading files for the county that she is CC so she SHOULD always be notified whether its a successful or failed upload.

**Comment by richpomfret** [comment] 2019-08-12 16:21
Could we get more info here? A successful case and failure case ideally required.

**Comment by SteveBiggs** [comment] 2019-08-14 10:02
From Linda:

I uploaded a file for a transcriber, who is no longer in my syndicate, and because I had copied and pasted the header of the file I accidentally missed off the + (as in +INFO) so his new coordinator received the error message when the file didn't upload successfully and I didn't so I had no idea it had malfunctioned.  
The file just seemed to disappear into thin air and it was only when I mentioned it to Ali (WRY) that it solved a mystery for her as well, as she wondered why she was getting an error message on a file that hadn't uploaded successfully for NRY.

However when a file uploads successfully I receive a message to say that it has done so. 

If you want to know specifics this is the file I had trouble with;

Re: Charlie/NRYRSRBA.csv processing encountered serious problem at at 2019-06-05 17:56:46 +0100

 The same file  NRYRSRBA  when it uploaded successfully I did receive an email.

Along with various others that I can list if you wish.  Here are one or two;

NRYAISBA/NRYAISBU/NRYAISMA
NRYBEDBA/NRYBEDBU/NRYBEDMA

**Comment by suffolkroots** [comment] 2019-10-25 11:43
Rich requested info---
I received an email yesterday (which I forwarded to Linda as she still does not receive them) re a failed upload for NRYDANBA 11.02.  The file was too large.
At the bottom it stated "**This email was sent to the syndicate coordinator and data managers.**"
No mention of the CC for file involved. Why??

**Comment by SteveBiggs** [comment] 2019-10-25 13:05
The system has been designed such that the SC looks after the transcribers so any issues such as file errors or files too large, etc. are reported to the SC to deal with. If they can't deal with it, then the DM gets involved.

Would it help if the transcriber in question was transferred to Linda's syndicate?

**Comment by suffolkroots** [comment] 2019-10-25 13:29
QED the design is at fault. 
CCs  who wish to look after their own county files, should be informed of any problems incurred whilst doing so.
This transcriber is with me as he moved from NRY to transcribe for WRY. Moving him back would just transfer the problem.
Add CC to the mail list. Simples.

**Comment by SteveBiggs** [comment] 2019-10-25 14:03
The problem here is that the transcriber has transferred from NRY to WRY syndicate, but the NRY CC/SC is changing/uploading files for the transcriber and needs to be informed if there are any errors. I agree with @suffolkroots that the CC should be added to the recipients.

**Comment by Sherlock21** [comment] 2019-10-25 18:13
It seems to me that the error lies in the fact that the Transcriber has changed from NRY, to WRY but still gets the NRY CC to upload his files.

**Comment by Sherlock21** [comment] 2019-10-25 18:13
It seems to me that the error lies in the fact that the Transcriber has changed from NRY, to WRY but still gets the NRY CC to upload his files.

**Comment by suffolkroots** [comment] 2019-10-26 08:30
@Sherlock21--- nothing to do with transcriber---these are historic files being amended by CC.

@SteveBiggs thank you for understanding the problem. I look forward to CC being added to recipients.

**Comment by Captainkirkdawson** [comment] 2019-11-02 21:34
The solution is not quite as it may seem at first glance.
We DO send emails to both CC  AND SC on both success and failures PROVIDING the failure is not catastrophic.
To determine who is the CC we look up the county to which the batch belongs. If the processing is catastrophic then we have never determined the county to which the batch belongs hence we cannot determine the CC who should receive the message. ie there have been no data lines processed
Now before you say extract the county from the file name it is important to remember that there is no requirement for the file name to include the county name. A file can have any name. By CONVENTION  most transcribers and coordinators do include the Chapman Code in the name as the first 3 characters. But some do NOT. 
We could look at the file name to see if it contains a valid Chapman Code and use that but we will clearly miss some files.

**Comment by suffolkroots** [comment] 2019-11-03 07:01
@Captainkirkdawson---so the CC who uploaded the catastrophic file must remain in ignorance, whilst the SC who has nothing to do with it passes it to DM who immediately refers to---guess who?---CC.
Perhaps CCs are deemed too lowly and fragile to be able to deal with their own county's catastrophic  files?
I look forward to CC being added to recipients.

**Comment by Captainkirkdawson** [comment] 2019-11-03 14:00
Clearly you did not read the post. On a catastrophic failure we do NOT know the county nor therefore the county coordinator involved

**Comment by suffolkroots** [comment] 2019-11-03 17:47
@Captainkirkdawson  I read the post and understood a catastrophic failure in planning and organisation.
I look forward to CC being added to recipients.

**Comment by richpomfret** [comment] 2019-11-06 17:08
We can try and find this out by processing the filename to potentially determine the county.

**Comment by Captainkirkdawson** [comment] 2019-11-14 21:54
@SteveBiggs have fixed the issue; involved a rewrite of the mail processing of both success and failure. So it will NEED a complete test as a transcriber, as a SC and as a CC.
I have tested but!
It is running on test3 so emails will be live

**Comment by Captainkirkdawson** [comment] 2019-11-19 17:30
Needs testing on test3 urgently to make sure it works as expected

**Comment by richpomfret** [comment] 2019-11-21 17:16
@SteveBiggs @Sherlock21 could I ask you both to help test this for Kirk? Otherwise this will stop us from deploying soon.

**Comment by SteveBiggs** [comment] 2019-11-22 10:50
Sorry, I've been rather busy with other things but @suffolkroots has taken the initiative to test it with Linda.

**Comment by Captainkirkdawson** [comment] 2019-11-23 15:29
It is unfortunate that there has been no feedback that the processing emails work or do not work on test3. The mail logs show that no one has processed a batch upload or replace on test3 since Oct 27 hence at this point we cannot proceed with the latest release

**Comment by suffolkroots** [comment] 2019-11-23 17:47
Kirk---I uploaded/replaced several yesterday on Test 3. Linda and I have only just come on board with this--a little bit of slack would be appreciated.

**Comment by Captainkirkdawson** [comment] 2019-11-23 18:33
Sorry Ali
But it is urgent as it is holding up the latest release.
The test3 logs show no processing messages from yesterday. If that is so then "Huston we have a problem"

**Comment by suffolkroots** [comment] 2019-11-23 18:37
As I replaced so many times, there is only one 22/11/2019 in my files list on Test 3. But it is there, and the record of earlier activity on 22/11 will be available to EricB. Yes, there is certainly a problem with your mail logs.

**Comment by suffolkroots** [comment] 2019-11-23 18:54
The mail I received re my final upload on 22/11 will have been copied to Steve Biggs, EricD and EricB as it was a "catastrophic failure"

**Comment by richpomfret** [comment] 2019-11-23 19:30
Would it be possible to run a few more processing file tests @suffolkroots @SteveBiggs and doublecheck this on TEST3? There could well be an issue with processing logs if you are running tests but they are not being recorded in the logs. Thank you for helping out here Ali.

**Comment by Captainkirkdawson** [comment] 2019-11-23 20:31
The mail log show
I, [2019-11-22T10:15:00.708558 #97888]  INFO -- : #<Mail::Message:17333092660, Multipart: false, Headers: <Date: Fri, 22 Nov 2019 10:15:00 +0000>, <From:  FreeREG Servant <freereg-processing@freereg.org.uk>>, <To: ali.hill.wry@gmail.com>, <Cc: ["ericbooker8@gmail.com", "freereg.edickens@gmail.com", "steveferring+DM@gmail.com"]>, <Message-ID: <5dd7b524a642d_17e6040300c56030798@vervet.freebmd.org.uk.mail>>, <Subject: JanetOgden submitted an action for file/batch WRYCALBU11.csv at 2019-11-22 10:15:00 +0000 that was too large for normal processing>, <Mime-Version: 1.0>, <Content-Type: text/html>, <Content-Transfer-Encoding: 7bit>>
Which is the correct routing I believe for a file that is too large
If you submitted that file then I happily accept that as an indication that mail is being logged. Unfortunately it is a special case mailing. It was caught and rejected before it entered the processing cycle. It is neither a "normal" processing email nor a "catastrophic" one. As a result I do not have any independent verification on test3 that  a file is uploaded or replaced and the processing system sends out an appropriate message.

**Comment by Captainkirkdawson** [comment] 2019-11-23 20:37
Really all I need at this point is someone to upload/replace a file and assure us that the email comes out correctly.

**Comment by richpomfret** [comment] 2019-11-23 21:14
Got a file for me? I'll try - although I am unsure of the exact test process for this, if I upload as a transcriber (new batch) will that be sufficient?

**Comment by Captainkirkdawson** [comment] 2019-11-23 21:19
Some sent

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by richpomfret** [comment] 2019-11-23 21:44
Ok i've tested a load of them (editing them to input errors) and uploaded. A few error emails have come through listing the issues.

**Comment by SteveBiggs** [comment] 2019-11-23 23:36
I've received 18 processing emails as Rich's SC. All of them, including the catastrophic failures are also copied to Julie, the CC for NFK so it would appear to be working correctly now:
![image](https://user-images.githubusercontent.com/25303607/69486964-dbb9a680-0e49-11ea-8875-a97a320ecd71.png)

**Comment by suffolkroots** [comment] 2019-11-24 11:00
I have received 2 emails as CC WRY re Rich's uploads---eg
richpomfrets/WRYTESTMA1Fs.csv processed at 2019-11-23 21:48:49 +0000 with  errors over period -
Rich,

The file submitted for processing has been completed. Please review the following report.
Started on the file WRYTESTMA1Fs.csv for richpomfrets at 2019-11-23 21:48:46 +0000.

Flexible csv flag detected. The next line will be taken a column specification.

Will use the following column specification ["chapman_code", "place_name", "church_name", "register_type", "register_entry_number", "marriage_date", "groom_forename", "groom_surname", "groom_age", "groom_parish", "groom_condition", "groom_occupation", "groom_abode", "bride_forename", "bride_surname", "bride_age", "bride_parish", "bride_condition", "bride_occupation", "bride_abode", "groom_father_forename", "groom_father_surname", "groom_father_occupation", "bride_father_forename", "bride_father_surname", "bride_father_occupation", "witness1_forename", "witness1_surname", "witness2_forename", "witness2_surname", "witness3_forename", "witness3_surname", "witness4_forename", "witness4_surname", "witness5_forename", "witness5_surname", "witness6_forename", "witness6_surname", "notes", "notes_from_transcriber", "marriage_by_licence", "film", "film_number"] The county code at field is invalid at line 1.
The place name at field is invalid at line 2.
The church name St Paul is not in the database for at line 2.
FREEREG:CSV_PROCESSOR_FAILURE: richpomfrets WRYTESTMA1Fs.csv at line 3 crashed the processor.

**Comment by Captainkirkdawson** [comment] 2019-11-24 15:13
The testing done by @richpomfret has confirmed that the revised code provides the CC with information even with catastrophic failures of the processor provided the file name contains the Chapman Code. It also identified an unintended consequences coding issue that has been fixed. 
Thank you all for this testing.Will proceed with the latest release.

**Closed as completed** 2019-11-24 16:00 UTC
Labels: Actor: county coordinator, Actor: syndicate coordinator, P17
