### ISSUE TITLE
re batch listings layout snag (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#29] opened 2014-09-26 08:55 UTC
Issue reported by **ericb** at 2014-09-26 08:55:16 UTC
Time: 2014-09-26T08:53:37+00:00
Session ID: 22c97e7bafcda84cbd25c8ac3bc22c6b
Problem Page URL: [/manage_resources/539a6a3ceca9eb57f1000550](/manage_resources/539a6a3ceca9eb57f1000550)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/refinery/login?](http://xanthus.freereg2.zomo.co.uk/refinery/login?)
Reported Issue:
Hi. this is in this new reporting format, to give it a number. But the attachment that you need is in an email.

as is rest of info.
EricB

**Comment by Captainkirkdawson** [comment] 2014-10-30 13:59
Don't know what the issue is

**Comment by graphiclunarkid** [comment] 2014-11-06 16:15
Closing as cannot reproduce

**Closed as completed** 2014-11-13 17:25 UTC
Labels: invalid
