### ISSUE TITLE
Updating of email address is not working even though the response was Successful (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#712] opened 2015-12-09 21:30 UTC
Issue reported by **REGManager** at 2015-12-09 21:30:16 UTC
Time: 2015-12-09T21:24:07+00:00
Session ID: 49bdb8f59d7e6736fa3a54e6e513dca9
Problem Page URL: [/userid_details/54fdaf8ae9379043ed000025](/userid_details/54fdaf8ae9379043ed000025)
Previous Page URL: [http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
Am trying to update UserID RichardHoward to the email address richardg.howard@btinternet.com but although the update was marked as Successful, the email address has not changed.  I have gone back to My Actions and in again but still the same.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2015-12-09 23:36
email is already in use for Richard (Richard Hooward) of the Norfolk syndicate

**Comment by edickens** [comment] 2015-12-10 07:39
But why can't I amend it as SysAdmin?  It is an amendable field and the report said that the  update was successful.  The reason for my doing Richard was that we have not heard from Julie for a while and he needs to access his account.
I see now that it did not do it for Damien on 9th as well, even though I got the report that the update had been successful.   And Damien is in my Syndicate.  E

**Comment by Captainkirkdawson** [comment] 2015-12-10 15:11
Duplicate of 525

**Closed as completed** 2015-12-10 15:11 UTC
Labels: bug, duplicate
