### ISSUE TITLE
Issue with dates (Mick)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#715] opened 2015-12-10 23:28 UTC
Issue reported by **Mick** at 2015-12-10 23:28:21 UTC
Time: 2015-12-10T23:23:36+00:00
Session ID: 462a34c605ce7d0e58d6f2d189e43d60
Problem Page URL: [/freereg1_csv_entries/566a0943f493fdc8b70011c4](/freereg1_csv_entries/566a0943f493fdc8b70011c4)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries/566a0943f493fdc8b70011c4/edit](http://freereg2.freereg.org.uk/freereg1_csv_entries/566a0943f493fdc8b70011c4/edit)
Reported Issue:
In this particular record the birth date is 05 Oct 1885 and the baptism date is Dec 1886.
This flagged up an error saying that the birth date was more recent than the baptism date which is not true.
When I amend the baptism date to 01 Dec 1886 the record is deemed acceptable.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2015-12-11 05:12
Duplicate of 705

**Closed as completed** 2015-12-11 05:13 UTC
