### ISSUE TITLE
181645751 Register type displayed as Unspecified when file displays Parish Register (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1378] opened 2020-10-03 11:49 UTC
Issue reported by **LINCC** at 2020-10-03 09:09:11 UTC
Time: 2020-10-03T08:49:44+00:00
Session ID: 0e7d5d1fb15049cdd05b6e0fa50a1a95
Problem Page URL: [/search_queries/5f783b27f493fdf97e5018f1?locale=en](/search_queries/5f783b27f493fdf97e5018f1?locale=en)
Previous Page URL: [https://www.freereg.org.uk/search_queries/new?locale=en&search_id=5f783aa6f493fdf97e50186d](https://www.freereg.org.uk/search_queries/new?locale=en&search_id=5f783aa6f493fdf97e50186d)
Reported Issue:
I have raised this point several times via email but it seems to have been missed every time because it was an addition to another point. I thought that is was something only CC's see. But it is not.

Today (3 Oct 2020) I carried out a normal FreeREG search, the results of which are attached. I have highlighted the records in question. They are showing the register type as "Unspecified". However, the file that contains them has a register type of "Parish Register". This is very misleading for researchers.

I suspect that the register type was changed from "Unspecified" to "Parish Register" during my data cleanup exercise. I cannot remember whether this conversion was done by "Relocate" or "Change Register Type". When either of these is carried out, the records within the file, as well as the file itself, should be changed to the new register type - not just the file and not the records.
https://www.freereg.org.uk/uploads/feedback/screenshot/5f783fb7f493fdf97e50302d/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment] 2020-10-14 17:08
Issue is that changes are not propgrated to every place.

Resolving this is a major task.

Consider removing 'relocate' action - with download, delete (using find/replace in notepad) and upload being used.

@edickens to find out who is using this tool and talk to, then to change method.  @PatReynolds to write story on quality control / survey to see the state of the database.

**Comment by edickens** [comment] 2020-10-19 11:05
I have consulted with a group of CCs who use this Action.
Kirk, will you please Disable"Relocate Batch", "Change Register Type" and "Relocate Church".  But do not remove the coding as we hope to Enable these Actions again in the future.
These three Actions all require the File to be changed to match their new location.  So, for now, it is safer to Download the File or Batch, Edit it, and it is recommended that you bulk replace the full set of County, Place and Church with Register Type, Upload this amended file then Delete the old version.  This is the safest and surest way to ensure that everything ties up.
Thanks Eric

**Comment by edickens** [comment] 2020-10-21 10:56
Since asking for this change, Michael, Eric Booker, Amanda and others have said that they still need to use the Relocate Action.  The problem is that, if you download an old file, then upload it again, "errors" are found, particularly in the date format.
So please do not disable these Actions for now.
However, we need to find out what is going wrong.  It seems to be with the relocate of Register Type rather than Place, Church or Batch.  It is really not necessary to Relocate an Unspecified Register Type, if it came from FR1.  We should stop doing this for now.  So just use Relocate Batch.
Does anyone have any idea which of the Relocates is causing the problem?

**Comment by Sherlock21** [comment] 2020-10-21 11:51
I will do a test in T3 - for a :IN Placename and see what happens

it is name change for KIRKBY LAYTHORPE

and should be Kirkby la Thorpe

some 2200 records of all types in 5 batches across Baptisms, Marriages & Burials

I will let you know how it goes.

Eric B

On 21 Oct 2020, at 11:56, Eric Dickens <notifications@github.com> wrote:


Since asking for this change, Michael, Eric Booker, Amanda and others have said that they still need to use the Relocate Action. The problem is that, if you download an old file, then upload it again, "errors" are found, particularly in the date format.
So please do not disable these Actions for now.
However, we need to find out what is going wrong. It seems to be with the relocate of Register Type rather than Place, Church or Batch. It is really not necessary to Relocate an Unspecified Register Type, if it came from FR1. We should stop doing this for now. So just use Relocate Batch.
Does anyone have any idea which of the Relocates is causing the problem?

**Comment by Sherlock21** [comment] 2020-10-21 13:21
My test in T3 worked perfectly correctly - from the user’s point of view ( not having access to any coding)

The onscreen messages were correct.
then my session timed out with the appropriate Warning

I waited 20 minutes or something like that, and logged on to T3 again to view LIN Placenemes.

the Kirkby Laythorpe place was still there but it had NO CHURCH AND THEREFRORE  NO RECORDS showing.

I did a user search (t3) for a person at random ( Baptism on Josiah Smith 1700-1740) and the result was correct: None there.

I did another view of The new place name Kirkby la Thorpe which was now populated by the church - correct
and the 5 existing batches - correct.
A user search for same Josiah Smith gave expected result - correct again.

Next step therefore was to delete (ie disable) the redundant place Kirkby Laythorpe	done and correct.

SO provided one does not jump the line before the timeout warning is received, I see nothing wrong with this feature.

Eric B

On 21 Oct 2020, at 12:51, Eric Booker <ericbooker8@gmail.com> wrote:

I will do a test in T3 - for a :IN Placename and see what happens

it is name change for KIRKBY LAYTHORPE

and should be Kirkby la Thorpe

some 2200 records of all types in 5 batches across Baptisms, Marriages & Burials

I will let you know how it goes.

Eric B

On 21 Oct 2020, at 11:56, Eric Dickens <notifications@github.com <mailto:notifications@github.com>> wrote:


Since asking for this change, Michael, Eric Booker, Amanda and others have said that they still need to use the Relocate Action. The problem is that, if you download an old file, then upload it again, "errors" are found, particularly in the date format.
So please do not disable these Actions for now.
However, we need to find out what is going wrong. It seems to be with the relocate of Register Type rather than Place, Church or Batch. It is really not necessary to Relocate an Unspecified Register Type, if it came from FR1. We should stop doing this for now. So just use Relocate Batch.
Does anyone have any idea which of the Relocates is causing the problem?

**Comment by suffolkroots** [comment] 2020-11-01 19:43
I sympathise with Michael re this problem.
I have today responded to contact action request 184187303, clicking on the file link provided leads to Unspecified, when the file in question is Parish Register.

![Capture](https://user-images.githubusercontent.com/10379655/97812641-894c5100-1c7a-11eb-8fa4-a2d8453c85c7.JPG)

**Comment by edickens** [comment] 2020-11-05 22:44
Jackie (SOM Coord) has found this....

Hello Eric
The other time when the record shows as Unspecified even though it is not, is when I have clicked on the Record link in a contact. 

Once the record has been edited it does return to PR or whatever, but it is quite a nuisance to not know which Register you are editing. Often in Somerset there is more than one register, and my reply might differ if I knew it were the Dwelly's for instance rather than the PR.

Is this something that is known about?

Jackie, Somcoord

**Comment by Sherlock21** [comment] 2020-11-07 11:17
Hi, EricD

I am not involved in anything with Jackie at the moment - sorry.


eb

On 5 Nov 2020, at 22:44, Eric Dickens <notifications@github.com> wrote:


Jackie (SOM Coord) has found this....

Hello Eric
The other time when the record shows as Unspecified even though it is not, is when I have clicked on the Record link in a contact.

Once the record has been edited it does return to PR or whatever, but it is quite a nuisance to not know which Register you are editing. Often in Somerset there is more than one register, and my reply might differ if I knew it were the Dwelly's for instance rather than the PR.

Is this something that is known about?

Jackie, Somcoord

**Closed as completed** 2021-04-07 21:17 UTC
