### ISSUE TITLE
Search dies

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#37] opened 2014-10-30 14:25 UTC
EricB reported on August 27

Doing a search of Baptisms in Northamptonshire / Barby + 20 Km

it falls over immediately.
Same if i use Miles units.

If I omit the radius search, then it works OK.

![screen shot 2014-08-27 at 13 54 29](https://cloud.githubusercontent.com/assets/2874694/4844930/79526ebc-6040-11e4-9204-3492f17cdbef.png)

**Comment by graphiclunarkid** [comment] 2014-12-01 14:22
Possible duplicate of #38

**Comment by Captainkirkdawson** [comment] 2014-12-13 04:03
Unable to duplicate

**Closed as completed** 2014-12-18 15:49 UTC
Labels: bug, Actor: researcher
