### ISSUE TITLE
197218369 Website Problem (kirby)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1423] opened 2021-04-02 10:17 UTC
Issue reported by **kirby** at 2021-04-01 14:52:49 UTC
Time: 2021-04-01T14:51:10+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
i received a message whilst performing a search for James Anderson in Angus/Forfarshire. I've included a screen shot. I had not requested specific records in the search [B/M/D] and felt there may be too many James Anderson entries. I selected Marriage and had no results.
https://www13.freereg.org.uk/uploads/contact/screenshot/6065de41f493fd20f1a8a885/Screen_Shot_2021-04-01_at_10.50.39_AM.png

**Comment by SteveBiggs** [comment] 2021-04-02 10:21
Nor clear what the problem is with this search. If I enter just the surname and the county it comes back with Too many results which is fair enough, but add a forename and it says 'Your search encountered a problem please contact us ....'?

**Comment by SteveBiggs** [comment] 2021-04-02 10:23
The issue appears to be the Baptisms. If I select Marriages only there are 42 results, Burials only there are 13 results, but select Baptisms only gives the same Problem message.

**Comment by Captainkirkdawson** [comment] 2021-04-04 22:04
This is very strange. The screenshot giving a missing page error may be totally misleading. The error reported by @SteveBiggs is very different. **Your search encountered a problem please contact us with this message**. This error is reproducible with searches for James Anderson in ANS. More specifically with Dundee. It is not apparent if a time band is entered. The error from the logs is serious. ` Search had a problem Performing an update on the path 'search_date' would modify the immutable field 'search_date' (66) (on mongo6.freeukgen.org.uk:27017`. However a search is not attempting to update any record.. Do we have a hardware issue????

**Comment by Sherlock21** [comment] 2021-04-05 18:30
Has someone removed the url 
https://www13.freereg.org.uk/uploads/contact/screenshot/6065de41f493fd20f1a8a885/Screen_Shot_2021-04-01_at_10.50.39_AM.png
because when I tried to log on to it, I got the system error message "You have requested a page that does not exist"

I was going to have a look at the actual files for Baptisms in Angus & Forfarshire and see what they look like.

**Comment by Sherlock21** [comment] 2021-04-05 18:46
Interesting problem here indeed.
I eventually found the records for County Angus, and traced the issue down to the place of Dundee.
Here there are only Baptism records, all by the same transcriber: Anne according to the file names. but it looks as though some files have been
records occupy 7 files. of very varied quantities of Baptism events in each.
I will download them and have a look at content. I was wondering if there is a mix of 'Flexi files and old original file type. - but as latest file is  2006 and revised in 2018 so I think that not an options.

I will have a snoop at the source data later.

**Comment by Sherlock21** [comment] 2021-04-05 19:20
Looking at production, 
in file ANSDEEBA20.CSV (by Anne) I notice there is an oddity in the file header.
it shows thus:- #,CREDIT,"",
ie there is "" in field 3, compared with the others which contain just the first 2 fields.
beyond that, I didn't see anything odd
and if I look at the above file using my word editor, I see there are many Andersons in the file. ( I could not count them)

HOWEVER when I do the same basic search in T3, for Baptism / James Anderson / Dundee, the search runs properly and returns 90 baptisms.
If I run it without the BMD criteria, it tells me: too many records. -

SO it that any use to you?

**Comment by PatReynolds** [comment] 2021-04-14 16:10
May be resolved by the new server.

**Comment by Captainkirkdawson** [comment] 2021-05-11 20:03
@SteveBiggs you may wish to review now we are running in the new servers. I believe the problem to be resolved

**Comment by SteveBiggs** [comment] 2021-05-12 18:39
Looks good to me now. I've asked the originator to check too.

**Closed as completed** 2021-05-18 17:39 UTC
