### ISSUE TITLE
71077358 Search result display is now wrong if Place Name contains text in brackets (xxx) (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#947] opened 2017-04-03 19:10 UTC
Issue reported by **ericb** at 2017-04-02 15:42:38 UTC
Time: 2017-04-02T15:32:59+00:00
Session ID: 8b4b712233f61320233f9d8ac54b1c9a
Problem Page URL: [/search_queries/58e119a9f493fd540a1ad82e](/search_queries/58e119a9f493fd540a1ad82e)
Previous Page URL: [https://www.freereg.org.uk/search_queries/new](https://www.freereg.org.uk/search_queries/new)
Reported Issue:
Some Places have names like Drayton (Martock). but in a search report, this has now got screwed up and comes out wrong:-
-see next report for the next attachment!
 
http://www13.freereg.org.uk/uploads/feedback/screenshot/58e11beef493fd540a1ad85d/Active_Places_listing_name.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58e11beef493fd540a1ad85d/Active_Places_listing_name.jpg)

**Comment by ghost** [comment] 2017-04-03 19:13
![search_result_listing](https://cloud.githubusercontent.com/assets/20557838/24626700/0c325296-18aa-11e7-9bd2-f28f0e4dc901.jpg)

**Comment by Captainkirkdawson** [comment] 2017-04-03 21:09
Place (church) is  "Drayton (Martock) (St Catherine)". Extraction hasa problem

**Comment by Captainkirkdawson** [comment] 2017-04-03 23:12
A fix has been developed and applied to test3. Could @Sherlock21  and others please test and ensure there are no regressions

**Comment by Captainkirkdawson** [comment] 2017-04-03 23:13
Please note there was a similar problem with the search record display since it used the same code

**Comment by Sherlock21** [comment] 2017-04-04 07:05
Thanks.

I will have a go with it later on during the day (today, tuesday)

**Comment by Sherlock21** [comment] 2017-04-04 08:32
Tested this fix out using the same file that was quoted in the Problem Report and the code  works fine now.
Confirmed the test on another SOM place name of the same style.

CONCLUSION: this is a complete success.

**Comment by Captainkirkdawson** [comment] 2017-04-04 14:14
Do you have any other unusual formats of place names?

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment] 2017-04-04 15:56
I did give it a thought, and NO.

there is only this one, which is because in the one County this is my way of distinctly identifying every Place - the bit in brackets is a Main Place  that the place is near to and so this way, ALL are distinct.

Other things to do with Places:-
Some Place names with have hyphens like Chorlton-cum-Hardy - and some just have the multiple words without hypens.

Multi word names may or maynot have each starting with a capital letter.

There are one or two others of the style of Ashton D’Newtown		-not really this actual name but I could not remember it - its of this form though.

And that is all. I did not test any of these this time round - just though we were looking at the brackets problem.

After dinner, I can try and find one of each kind.
Eric

**Comment by Captainkirkdawson** [comment] 2017-04-04 16:21
The Bracket in the place name was the problem but when it does not work
correctly for one does it work correctly for other non standard situations.
Hence the question.

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment] 2017-04-04 19:40
I will have a go at this tomorrow - too busy with house things now.
E.

**Comment by Sherlock21** [comment] 2017-04-04 20:03
heres the 3 OK tests for the odd place names:-

ALL GOOD.














This one is Westward Ho! withthe exclamation mark. Correct.

All god.

EB

**Comment by Captainkirkdawson** [comment] 2017-04-04 23:33
TY

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Closed as completed** 2017-04-26 15:58 UTC
Labels: bug
