### ISSUE TITLE
50697647 Files not being processed (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#780] opened 2016-08-13 13:23 UTC
Issue reported by **steveroland** at 2016-08-09 18:40:47 UTC
Time: 2016-08-09T18:37:00+00:00
Session ID: 586159dc329b146337604e04dcb923d1
Problem Page URL: [/physical_files?page=](/physical_files?page=)
Previous Page URL: [http://www.freereg.org.uk/physical_files](http://www.freereg.org.uk/physical_files)
Reported Issue:
Occasionally a file that is uploaded for processing never gets processed but sits in the base files area. When I notice it, I have to go in and tell it to process in FR2 manually.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57aa23aff493fd43fe000951/Capture.jpg)

**Comment by Captainkirkdawson** [comment] 2016-08-13 15:28
A statement like this is impossible to investigate. 
What needs to happen is that the coordinator needs to give us an example before taking action so that we can investigate.
Until then it cannot be defined as a bug. 
It could just be that the transcriber uploaded the file and did not ask for it to be processed.

**Comment by Captainkirkdawson** [comment] 2016-10-31 17:56
Duplicate of 825. The latter is more relevant

**Closed as completed** 2016-10-31 17:57 UTC
Labels: duplicate, needs info
