### ISSUE TITLE
52423518 Missing Actions in my list (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#792] opened 2016-08-29 18:51 UTC
Issue reported by **steveroland** at 2016-08-29 18:05:18 UTC
Time: 2016-08-29T18:01:04+00:00
Session ID: 391321463061ce855aa9c0356ed859aa
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2016-08-29+17%3A58%3A52+UTC&session_id=391321463061ce855aa9c0356ed859aa&user_id=steveroland&problem_page_url=%2Fmanage_resources%2Fnew&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fcms%2Frefinery%2Flogin&feedback_type=issue](http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2016-08-29+17%3A58%3A52+UTC&session_id=391321463061ce855aa9c0356ed859aa&user_id=steveroland&problem_page_url=%2Fmanage_resources%2Fnew&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fcms%2Frefinery%2Flogin&feedback_type=issue)
Reported Issue:
I am coordinator for Surrey & Sussex, but do not have 'Manage Syndicates' in my available actions. Nor do I have 'Contacts' or 'Feedback' that I used to have. My role is Data Manager as well.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57c4795ef493fdf175d871e8/Capture.jpg)

**Comment by Captainkirkdawson** [comment] 2016-08-30 14:31
Need confirmation this remains an issue

**Comment by Sherlock21** [comment] 2016-08-30 15:58
Your collection looks exactly like mine, Steve - And I used to have more than this set - I can t remember all of what it used to be.
So far I have not needed any of the missing Actions though.

Eric B

**Comment by PatReynolds** [comment] 2016-09-02 14:35
Duplicate of #784 ?

**Comment by Captainkirkdawson** [comment] 2016-09-02 15:07
Resolved

**Closed as completed by Captainkirkdawson** 2016-09-02 15:07 UTC
Labels: needs info
