### ISSUE TITLE
Website Problem (Damian Cummings)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#233] opened 2015-05-23 19:19 UTC
Issue reported by **Damian Cummings** at 2015-05-23 19:19:37 UTC
Time: 2015-05-23T19:10:07+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts](http://www13.freereg.org.uk/contacts)
Reported Issue:
I have a problem with printing an entry to PDF.  I always keep a copy of all records I use (as I'm sure many people do).  However, when I print to PDF, all the details come out on top of each other and are completely unreadable.  I have attached the PDF as it comes out.  I have not had this issue on any other page than freereg2.  I would greatly appreciate it if you could address this problem, as the new search engine is far improved over the original- thank you so much for the update!

Damian

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1432408777-30259-0213/Screen_Shot_2015-05-23_at_20.17.17.jpg)

**Comment by Captainkirkdawson** [comment] 2015-05-31 14:34
Duplicate of 366

**Closed as completed** 2015-05-31 14:34 UTC
Labels: duplicate
