### ISSUE TITLE
51660994 Coordinator reports extra menu options (Kirk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#784] opened 2016-08-21 13:20 UTC
Issue reported by **Captainkirk** at 2016-08-20 22:16:34 UTC
Time: 2016-08-20T22:10:59+00:00
Session ID: 6db72d1557168ebb8579601b04632624
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/5463b11ee937904abb029629](http://freereg2.freereg.org.uk/freereg1_csv_files/5463b11ee937904abb029629)
Reported Issue:
As CC I do not think I should have all these options. Am I correct?
To get to this point I had left a top level view of a batch screen for a few hours. I think I went into the crumb "Your Actions" and then logged on as normal. This resulted in the information on the capture.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57b8d6c2f493fd179e942edc/Capture.JPG)

**Comment by Captainkirkdawson** [comment] 2016-08-30 01:29
Duplicate of #789

**Closed as completed** 2016-08-30 01:29 UTC
Labels: Actor: county coordinator, Actor: syndicate coordinator
