### ISSUE TITLE
160744957 Problem sending a message (Pat)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1273] opened 2020-02-04 11:46 UTC
Issue reported by **PatReynolds** at 2020-02-04 11:22:37 UTC
Time: 2020-02-04T11:20:25+00:00
Session ID: 34e0c1a725c2c23511914427545a174b
Problem Page URL: [/messages/5e395366f493fdf042427640/select_recipients?locale=en&source=original](/messages/5e395366f493fdf042427640/select_recipients?locale=en&source=original)
Previous Page URL: [https://www.freereg.org.uk/messages/5e395366f493fdf042427640?locale=en&source=original](https://www.freereg.org.uk/messages/5e395366f493fdf042427640?locale=en&source=original)
Reported Issue:
Message did not sent. Error is logged - sorry, I did repeat, because the first time I sent I thought there was something odd about the highlighting in Transcription Agreement status.

    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2020-02-04 16:13
This is duplicate of [production][messages#update] SMTP To address may not exceed 2kB: "Eric Dickens <freereg.edickens@gmail.com>, Eric Booker <eric...#2219
Solution suggested there was
_Step 1 would be just transcribers. You could subset active transcribers by their open data status.
Unfortunately this is a system limit that I have no control over_

**Comment by richpomfret** [comment] 2020-02-04 17:37
Closing as duplicate.

**Closed as completed by richpomfret** 2020-02-04 17:37 UTC
