### ISSUE TITLE
171021929 Is there a restriction on the age allowed in burial records? (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1330] opened 2020-06-02 10:45 UTC
Issue reported by **LINCC** at 2020-06-02 10:05:29 UTC
Time: 2020-06-02T10:04:00+00:00
Session ID: 66f6e2ede4815f05b8d139a72e58813a
Problem Page URL: [/freereg1_csv_entries/5ed61f78f493fd7006345b90/error?locale=en&referrer=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F5ed61eedf493fd70063452ae%3Flocale%3Den](/freereg1_csv_entries/5ed61f78f493fd7006345b90/error?locale=en&referrer=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F5ed61eedf493fd70063452ae%3Flocale%3Den)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_entries/5ed61f78f493fd7006345b90/error?locale=en&referrer=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F5ed61eedf493fd70063452ae%3Flocale%3Den](https://www.freereg.org.uk/freereg1_csv_entries/5ed61f78f493fd7006345b90/error?locale=en&referrer=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F5ed61eedf493fd70063452ae%3Flocale%3Den)
Reported Issue:
Trying, online, to enter an age of 101y11m but it is not allowed.    

![Screenshot](https://www.freereg.org.uk)

E0 U6 S7 C6:P19

**Comment by SteveBiggs** [comment] 2020-06-02 10:47
From testing it appears that only the year is allowed from age 100 upwards. e.g. 99y11m is accepted but 100y11m is not. Is this by design?

**Comment by richpomfret** [comment] 2020-06-10 16:44
A bug, but won't effect too many.

**Comment by richpomfret** [comment] 2020-07-08 16:56
@PatReynolds to prioritise before moving it over.

**Comment by SteveBiggs** [comment] 2020-08-07 15:36
Comment from Michael Clarke today:

Has anything been done with regards to the 3-digit ages problem. If so, it still does not work. If not so, I have got files in LIN that have, validly, 3-digit ages and, at the moment, these records are recorded as "error records" so will not come up in any searches. It also means that nothing can be done with the file as it contains errors (another point that I have queried)

**Comment by Captainkirkdawson** [comment] 2020-08-08 15:41
Nothing. Still sitting in incoming

**Comment by PatReynolds** [comment] 2021-04-28 15:57
Needs to be explained in help: system does not accept, so just put in the years, and explain in the notes.

**Comment by DeniseColbert** [comment] 2022-12-21 15:17
@Vino-S to allow system to accept the same info as below 100 y

**Comment by DeniseColbert** [comment] 2023-02-15 15:15
Done on Test 3 closing

**Closed as completed by DeniseColbert** 2023-02-15 15:15 UTC
Labels: bug, documentation, P19
