### ISSUE TITLE
Search on a Placename that has no records generates erroneous results if Nearby used. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#248] opened 2015-06-10 13:13 UTC
Issue reported by **ericb** at 2015-06-10 13:13:01 UTC
Time: 2015-06-10T13:03:00+00:00
Session ID: d61e1384f368f7f480a32b7f0e63b1ce
Problem Page URL: [/search_queries/55783583f493fdaba700009b](/search_queries/55783583f493fdaba700009b)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/new?search_id=5578350cf493fdaba7000098](http://freereg2.freereg.org.uk/search_queries/new?search_id=5578350cf493fdaba7000098)
Reported Issue:
Example: Search for Thomas Bell/ NFK/ Wells-next-the-Sea / Baptisms/ no date restrictions.
you get nil results (correct)
Then do again and add: Nearby.
This time you get a full range of results ( part listing attached) for a variety of places all over  England. Including North Otterington in NRY. and others in other Counties.
Look at About/ Nearby to see why so far afield and see all these places have zero in distance away.
Now North Otterington is NOT in FR2 s a place but it does have an entry in RED and some records which happen to contain that  which was searched for.

This is probably because of the TQ gridref of Kirks. AND the fact that the place is given a default of zero distance away. - so a snag here.

BUt I also thought records that were against NotApproved places were excluded from the search results? and another snag here.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1433941981-66493-1082/Screen_shot_2015-06-10_at_14.02.24.jpg)

**Comment by Sherlock21** [comment] 2015-06-10 13:19
This snag report arises from my investigation of user report 
link: Ken_Andrews.NRYNOTBA.CSV.497

**Comment by Captainkirkdawson** [comment] 2015-06-13 19:24
System performs as expected. Wells-next-the-Sea is an unapproved name. Hence a nearby search is from the location of the unapproved place which is the Tower of London. So you will get other non approved places giving you results.
Specific problem will be fixed when Wells-next-the-Sea is fixed by the coordinator

**Closed as completed by Captainkirkdawson** 2015-06-13 19:24 UTC

**Comment by Sherlock21** [comment] 2015-06-13 21:43
Indeed it does match on GridRef as intended. BUT its a false GridRef. I know that, but the researcher does not know that and sees the result as totally wrong  since the "nearnby" places can be 100 miles away at apparent random. We should exclude any records form the Tower of London fictional code in all cases.

**Comment by Captainkirkdawson** [comment] 2015-06-13 22:00
No we should fix the data
