### ISSUE TITLE
Consider the placement of adverts on other pages.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#822] opened 2016-10-20 10:01 UTC
Based on learning from FreeCEN2
Inc. ad on main page section of Transcriber sign-up see #1320

**Comment by AlOneill** [comment] 2017-01-23 22:08
Again, each ad will require a skiplink (and destination) -- those who have to navigate by keyboard will need a way to skip over the 7 or more links in a single typical ad block.

**Comment by Captainkirkdawson** [comment] 2018-08-10 02:25
I(s this not a duplicate of #821

**Closed as completed by Captainkirkdawson** 2018-08-10 02:25 UTC
Labels: needs info, Non-phase specific
