### ISSUE TITLE
time out issues replacing a batch of my own (ericb/WRYDEWBA4.csv) (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#137] opened 2015-01-03 14:14 UTC
Issue reported by **ericb** at 2015-01-03 14:14:51 UTC
Time: 2015-01-03T13:52:01+00:00
Session ID: a461d86fb1859a8d8368fed44fd19136
Problem Page URL: [/freereg1_csv_files/547254abe93790ddb6000001](/freereg1_csv_files/547254abe93790ddb6000001)
Previous Page URL: [http://test2.freereg.org.uk/churches/54080e9aeca9eb02488eaa3f](http://test2.freereg.org.uk/churches/54080e9aeca9eb02488eaa3f)
Reported Issue:
I needed to correct a data error so chose: REPLACE .

That crashed with Timeout - Server did not respond in time msg to my browser ( in a fresh window) FR2 having disappeared off at the event time.
Seemed like it was about a couple of minutes of more possibly.

So as it seemed that the batch was still there in my collection, I went for try again, but DELETE the existing one, to be followed by straight UPLOAD a batch.

The DELET also timed out, same error msg on my browser.     

![Screenshot](http://test2.freereg.org.uk)

**Comment by Sherlock21** [comment] 2015-01-03 14:31
Looking at my list of files some 15 minutes later,  the file i was trying to delete is no longer listed in my own files list. - so the process continued despite loosing my connection to the server.

SO I will try and upload the corrected version now and watch my Network Activity monitor display.
and add another msg with the result. ( I can't have  this link open and do another logon session at same time!)

**Comment by Captainkirkdawson** [comment] 2015-01-03 19:47
See 138' this was caused by a transient stress on the server and to be expected from time to time as it is a shared test server

**Comment by Sherlock21** [comment] 2015-01-04 09:07
OK, Close this one and await moving over to the full production Server and then see what happens there?

**Closed as completed** 2015-01-04 16:50 UTC
