### ISSUE TITLE
lack of  displayed records (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#107] opened 2014-11-29 00:05 UTC
Issue reported by **ericb** at 2014-11-27 18:35:35 UTC
Time: 2014-11-27T18:31:27+00:00
Session ID: f09b4fff28d66e6d51a673547e5f5bf0
Problem Page URL: [/registers/540a15e2eca9ebd28e1b26f2](/registers/540a15e2eca9ebd28e1b26f2)
Previous Page URL: [http://test2.freereg.org.uk/churches/540a15e2eca9ebd28e1b26ef](http://test2.freereg.org.uk/churches/540a15e2eca9ebd28e1b26ef)
Reported Issue:
The placename CAM / Little Abington Pr shows it as Not Approved.
When I go to try and find the Batches for here, to look at the data, I see no Batches.

Is this because its one of those batches that have  blank data rows in it and thus it does not load correctly or something I seem to recall?

What ever the reason can you please advise the cause of this Place name & Church appearing here?    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2015-01-02 00:57
Left over from the rebuild the batches no longer contained the error in November. Duplicate of 109

**Closed as completed** 2015-01-02 00:57 UTC
Labels: duplicate
