### ISSUE TITLE
78139318 Login (Bernard)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#976] opened 2017-06-24 09:04 UTC
Issue reported by **dranreb** at 2017-06-23 09:21:58 UTC
Time: 2017-06-23T09:20:52+00:00
Session ID: 2db810c45629abe0665004e71300ac16
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: []()
Reported Issue:
The system fails to remember my password    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/594cddb6f493fd7decf33b39/_old_)

**Comment by Captainkirkdawson** [comment] 2017-06-24 11:30
We need more inforation on what is meant by this complaint.

Since he has logged in the system has remembered his password

**Comment by edickens** [comment] 2017-06-24 11:35
I think he is expecting "Auto-fill" of his password the next time he logs in.  The "Remember me" button I thought was going to be renamed "Stay logged in".  ED

**Comment by Captainkirkdawson** [comment] 2017-06-26 16:06
Duplicate of 923 which is in product backlog

**Closed as completed** 2017-06-26 16:18 UTC
