### ISSUE TITLE
156265708 Place name notes and Church notes seem to have gone. (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1264] opened 2019-12-14 17:13 UTC
Issue reported by **ericb** at 2019-12-14 15:08:28 UTC
Time: 2019-12-14T15:00:58+00:00
Session ID: d19609674a67f43bdfb3a689d4d6f5dd
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2019-12-14+15%3A00%3A17+UTC&session_id=d19609674a67f43bdfb3a689d4d6f5dd&user_id=ericb&problem_page_url=%2Fmanage_resources%2Fnew%3Flocale%3Den&previous_page_url=https%3A%2F%2Fwww.freereg.org.uk%2Fcms%2Frefinery%2Flogin&feedback_type=issue](https://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2019-12-14+15%3A00%3A17+UTC&session_id=d19609674a67f43bdfb3a689d4d6f5dd&user_id=ericb&problem_page_url=%2Fmanage_resources%2Fnew%3Flocale%3Den&previous_page_url=https%3A%2F%2Fwww.freereg.org.uk%2Fcms%2Frefinery%2Flogin&feedback_type=issue)
Reported Issue:
I did create Church notes for WRY/DEWSBURY/ All Saints church, and also WRY/TOPCLIFE/Congregational or may be MORLEY Old Methodist and they seem to have disappeared. Also, I know that Ali Hill reports that some she created have gone, but others remain! Same for  SOM / Jackie/

Have they been taken off deliberately or just fallen off? 

    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment] 2019-12-17 17:34
To test out adding notes and seeing if these save or not. @edickens to test.

**Comment by edickens** [comment] 2019-12-17 21:17
I have added a note to Devon, Morebath, St George, and it is still there after logging out and in again.  But EricB, do you mean that the notes are not there when you look under Transcriptions:-
https://www.freereg.org.uk/freereg_contents/Morebath/show_place?locale=en
because you are correct, the Note is not there, but then I don't know if they should ever have been.
If this is wrong, please let us know where you saw this problem.  We cannot reproduce it.

**Comment by Captainkirkdawson** [comment] 2019-12-17 21:28
I see it on transcriptions
![Morebath](https://user-images.githubusercontent.com/2874694/71035804-8f285a80-20d9-11ea-90b9-8075d911b576.JPG)

**Comment by edickens** [comment] 2019-12-17 22:33
But if you are not logged in:-
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/7a7505c8-e967-4c60-8293-fb0c3f83860e)

**Comment by edickens** [comment] 2019-12-17 22:34
Sorry.  Wrong clip.

**Comment by edickens** [comment] 2019-12-17 22:36
And I looked at the Place information.  In too much of a hurry.  Seems to be working fine.  TY

**Comment by richpomfret** [comment] 2020-03-17 17:46
Closing - will reopen if indeed it ends up being a problem.

**Closed as completed** 2020-03-17 17:47 UTC
Labels: needs info
