### ISSUE TITLE
17 P 112194199 some images in group unable to be allocated (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1105] opened 2018-07-24 23:08 UTC
Priority  17 (0	2	8	7)
Issue reported by **brobinson43** at 2018-07-22 13:03:19 UTC
Time: 2018-07-22T12:56:03+00:00
Session ID: b77888519ae3d34b78a4d034acb792f5
Problem Page URL: [/image_server_images/5a9ed01ef493fdbfcb9c1382/index](/image_server_images/5a9ed01ef493fdbfcb9c1382/index)
Previous Page URL: [https://www.freereg.org.uk/image_server_images/5a9ed01ef493fdbfcb9c1382/index](https://www.freereg.org.uk/image_server_images/5a9ed01ef493fdbfcb9c1382/index)
Reported Issue:
You will see that the images referred to in the attached screenshot from about the fifth one down have different filename formats than the earlier ones, and the system seems unable to allocate them to this transcriber. I do not know how this has happened. (All files would have initially had filenames like DSCN8788.JPG)
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b548097f493fd669b2d4635/Screen_shot_2018-07-22_at_10.57.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b548097f493fd669b2d4635/Screen_shot_2018-07-22_at_10.57.jpg)

**Comment by edickens** [comment] 2018-07-31 08:04
Having image names in this format is not unusual.  These images match what is on the image server and the images can be viewed.
I do not see any problems here.
Is this because part of the IG has been Assigned to a transcriber, so the server does not let you Assign any other images?
Is this a situation where the IG should say both Allocated and Being Transcribed, because part of the IG has been Assigned and part not?
![capture](https://user-images.githubusercontent.com/8876165/43446340-86ccaf42-94a0-11e8-9ac0-852bdfc989d2.JPG)

**Comment by edickens** [comment] 2019-11-05 11:42
Things seem to have changed and the problem cannot be reproduced.  Barrie and I will keep a look out for it in the future, but for now I will close this and create a new story if necessary.

**Closed as completed by edickens** 2019-11-05 11:42 UTC
Labels: ready, Image Server, P17
