### ISSUE TITLE
List of Batches does not order by Oldest first

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#1154] opened 2018-12-15 14:23 UTC
when viewing ones list of Batches, the option to order by Alphabetical File names works fine.

SO does Most Recent.

But Oldest does not work. - Warning Message says: Missing Page in Red.

**Comment by Captainkirkdawson** [comment] 2018-12-15 16:20
Caused by #1717 and will be fixed there

**Closed as completed** 2018-12-17 03:48 UTC
Labels: bug
