### ISSUE TITLE
Marriage date not being displayed (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#528] opened 2015-10-23 08:13 UTC
Issue reported by **REGManager** at 2015-10-23 08:13:04 UTC
Time: 2015-10-23T08:11:22+00:00
Session ID: c856d5b36d5a44d1f15c99061bb73fd0
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/55c6ddfff493fd857c024c9b](http://www.freereg.org.uk/freereg1_csv_files/55c6ddfff493fd857c024c9b)
Reported Issue:
In the Browse records and the Detail of each record, the Date of Marriage is not being displayed.
I have sent a separate email to Kirk because it has a number of screen prints.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2015-10-23 15:06
Why do we have 4 stories for one apparent issue #528, $523, #522 and #521

**Comment by Sherlock21** [comment] 2015-10-23 15:21
It happened in the course of trying to attach 3 different images from the screen. They are all the same issue. but since /i cannot edit nor deleted them on Safari, once made, this is what we have got.

**Comment by Sherlock21** [comment] 2015-10-23 15:22
I am referring to the 3 in my userid.

**Comment by edickens** [comment] 2015-10-23 17:02
```
They have been generated by different people?  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 23/10/2015 16:06, Kirk Dawson wrote:

```
  Why do we have 4 stories for one apparent issue #528, $523, #522 and #521
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment] 2015-10-23 18:46
Responding to #521, #522 , #523 and  #528 since they all deal with the same file.

The forename is not in the date field. There is no date in the date field.

The original was for  Unspecified for Christ Church in West Bromwich of Staffordshire when it was uploaded on 02-Nov-2014.

At some point it looks like it was downloaded and edited to put Pr on the church name. While doing that the date field was deleted. The file was uploaded on 22 Oct 2015 with no date entries.

+INFO,genghis17@comcast.net,PASSWORD,SEQUENCED,MARRIAGES,Windows-1252
#,CCC,Dale Braden,Staffordshire - Michael Clarke,STSWEIMA.CSV,25-Sep-2014
#,CREDIT,Dale Braden,
#,22-Oct-2015,,
STS,West Bromwich,Christ Church PR,1,"",William,HORTON,21,"",bachelor,Engineer,Loveday St,Christiana,WATSON,21,"",spinster,"",Loveday St,William,HORTON,Pistol filer,Thomas,WATSON,Labourer,Zephaniah,FIRKIN,Elizabeth,WATSON,Neither banns nor licence is specified. Groom & both witnesses sign X
STS,West Bromwich,Christ Church PR,2,"",Thomas,MORRIS,24,"",bachelor,Brick layer,Pritchett St,Phoebe,CLARE,22,"",spinster,"",Pritchett St,David,MORRIS,Maltster,William,CLARE,Gun stocker,Joseph,SANDBROOK,Mary Ann,SANDBROOK,Neither banns nor licence is specified. Witness 1 signs X
STS,West Bromwich,Christ Church PR,3,"",Samuel,DINGLEY,21,"",bachelor,Brick maker,Oldbury Road,Sarah,CUTLER,22,"",widow,"",Oldbury Road,Samuel,DINGLEY,Brick maker,Joseph,WAIN,Miner,Thomas,CROMPTON,Rebecca,WATERHOUSE,"Neither banns nor licence is specified. Groom, bride & both witnesses sign X"
STS,West Bromwich,Christ Church PR,4,"",Charles,COTTRILL,25,"",bachelor,Butcher,High St,Emma,WHITE,21,"",spinster,"",Clay Pit Lane,John,COTTRILL,Farmer,John,WHITE,Farmer,John,WHITE,Charlotte,WHITE,Neither banns nor licence is specified. Witness 1 signs X

**Comment by Sherlock21** [comment] 2015-10-23 18:56
Thanks, Kirk

I will get it fixed now we know that essential fact.

Ericb

**Comment by Captainkirkdawson** [comment] 2015-10-23 20:37
Looking further into this; it actually looks like these files were relocated; they have not been reprocessed as Physical Files shows no indication of any processing. Also the header information reflects the previous processing ie that are max and min dates and range information
Have run a number of tests with relocation of files just changing  the Register type and not been able to reproduce this effect.

**Comment by Captainkirkdawson** [comment] 2015-10-23 21:24
The relocation does not actually change the physical file that happens at the time of a download.. The  file was downloaded at 23:00 on the 21st. The file placed in the attic had a PR register status and the dates were intact. The file sitting in the folder has the same time which would indicate that there were no subsequent uploads. Puzzling.

**Comment by edickens** [comment] 2015-10-23 21:37
```
Does anyone want me to replace files from the Attic?  Just give me
UserID:Filename.  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman

**Comment by Sherlock21** [comment] 2015-10-24 08:19
I am thinking its a case of someone dabbling where they don't have the knowledge. Would this fit?
And so that would raise the question: have we got the permissions right. I hope we have  because EricD & myself don't want to end up doing everything! 
DO we need to review them though?

Do we store userID in the Audit trail which Kirk refers to? If not, should we?

Lastly: shall we just put this file right, and move on, on this occasion. Then worry more if it happens again?

**Comment by edickens** [comment] 2015-10-24 08:39
```
I think we should just put these files (there are more than one but
all in this UserID) right and then see if it occurs again.  We can't
really tell what happened and it does not seem to be in any other
UserID.  E

On 24/10/2015 09:19, Sherlock21 wrote:


  I am thinking its a case of someone dabbling where they don't
    have the knowledge. Would this fit?
    And so that would raise the question: have we got the
    permissions right. I hope we have because EricD & myself
    don't want to end up doing everything! 
    DO we need to review them though?
  Do we store userID in the Audit trail which Kirk refers to? If
    not, should we?
  Lastly: shall we just put this file right, and move on, on this
    occasion. Then worry more if it happens again?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment] 2015-10-24 08:58
OK EricD in this case shall I do it?
or should we get the CC to do. - please advise?

**Comment by Captainkirkdawson** [comment] 2015-10-25 00:15
The CC cannot. He has no access to attic. You two sort it out please

**Comment by Sherlock21** [comment] 2015-10-25 08:42
I extracted the correct file from the attic, changed the Register type ( which wa the change being= done and accidentally deleted the Marriage Dates data) and reloaded overnight in the id of dbraden.
Only to find this morning that there were 2 identical Marriage files there now! Mine ( with a note in the header) and one by the user!
I have deleted the latter to avoid confusion and locked mine. Surprisingly, mine was not locked as a result of me uploading in the Id of the user!

**Comment by Sherlock21** [comment] 2015-10-25 09:15
I did uploaded a file to rectify missing Marriage dates in dbrogan/STS/ STSWEIMA.csv last night, having deleted the existing version without Marriage dates.
BUT then this morning, I went to recheck and there were 2 copies of the file there!! both with same userid & file name
One was mine because I put a note in the header : reloaded be Data Manager and the other looked like been uploaded by the user or someone with access to use the userid. I have deleted that one!
But it seems the one I deleted was the product of the overnight F1 > FR update - which i though had now ceased.
The file I uploaded in the ID of dbrogan was not locked as i had expected to would be. so I locked it manually this morning to stop further interference.

**Closed as completed** 2015-11-04 19:20 UTC
