### ISSUE TITLE
88864283 Relationship field for a baptism

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1009] opened 2017-10-25 17:36 UTC
Issue reported by **Froggy7** at 2017-10-25 12:31:23 UTC
Time: 2017-10-25T12:16:43+00:00
Session ID: 588a981b2194e9761fac83caa70dda93
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
This is not strictly a problem but my suggestions for improvements to WinReg - if they are possible. This probably needs addressing to someone else but I am not sure who so would you please pass on to appropriate person.

1. In the 'Sex' columns of Baptisms and Burials is it possible to add 'child of' to the selection as it is not always stated clearly(particularly in Latin) whether male or female.
2. Is it possible to introduce superscript and subscript so that transcriptions may more accurately reproduce names in records. 
3. Same again for letter symbols so that names may be transcribed as they appear (Examples - Phoebe, Thomae).

Not suggesting any of these are of great importance but, IMO,  would be helpful.

Paul Froggitt

    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/59f0841bf493fde3b15786f8/_old_)

**Comment by edickens** [comment] 2017-10-26 10:45
1. I'm not sure if this has to match the Server validation.  Also, some fields in WinReg are lists to which you can add extra entries.  But cannot check yet if this is one of them.
2. The server does not accept these.  At least FR1 didn't does FR?
3. It depends on FR validation, but we certainly ought to accept some, particularly some of the standard clerical abbreviations such as + for Christ as in +opher.  But how would the search work?
(I have not replied to the sender. - E)

**Comment by SteveBiggs** [comment] 2017-11-06 10:06
1. You can add other options for the relationship in a burial via 'Settings'->'Lookup Tables'->'Burial  Relationships' (I have used "cousin of"), but this is not supported for baptism sex.

**Comment by Captainkirkdawson** [comment] 2018-02-09 00:10
Perhaps as part of #809 we should add a relationship field to the baptism collection so we can really do TWYS as well as have the inferred sex field

**Comment by SteveBiggs** [comment] 2018-02-09 12:35
I agree. A baptism never says the words 'male' or 'female' but says 'son of', etc. so we don't actually need the Sex field - Just have Relationship as in Burials.

**Comment by edickens** [comment] 2018-02-09 12:49
But would both be useful for analysis?

**Comment by SteveBiggs** [comment] 2018-02-09 13:07
Perhaps, but we should always TWYS, in which case the Sex would (should) virtually never be entered.

**Comment by edickens** [comment] 2018-02-09 13:13
We could now include some "Assumed" fields where the transcriber has some more information.  Such as my grandfather's MA which was transcribed as Wickens, but the signature field is obviously Dickens.
And that makes me think whether we need to define any extra fields/information where we may let researchers add something.  They can't change anything, but could fill in gaps, such as parents in old marriages.

**Comment by PatReynolds** [comment] 2018-02-09 14:14
On special characters (e.g. superscript, oe ligature) : Kirk said on #469 "FR2 supports all special characters in the CP1252 character codeset. It uses a conversion of that codeset into Unicode. If there are missing special characters then it is likely caused by WinREG which uses a subset of CP1252 that does not include a number of special characters. It uses iso-8859-1."

So FreeREG2 can cope with all the characters mentioned.

**Comment by Captainkirkdawson** [comment] 2018-02-11 20:30
@SteveBiggs can you check we have this in the list of new fields in #809. If so we can close this story

**Comment by SteveBiggs** [comment] 2018-02-11 22:54
Yes, we have a relationship field proposed in BA.

**Closed as completed** 2018-02-11 23:51 UTC
Labels: Could have, CSV needed
