### ISSUE TITLE
Reg codes in WinREG (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#640] opened 2015-11-23 13:50 UTC
Issue reported by **alsibk** at 2015-11-23 13:50:27 UTC
Time: 2015-11-23T13:36:56+00:00
Session ID: 96c22d3d4b67c562d968a248fe19f584
Problem Page URL: [/manage_counties/select_action](/manage_counties/select_action)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
There were earlier today 3 churches in Methley, the result of a transcriber trying to deal with Mike Fry's new coding system.

1 St Oswald (TR)

(TR no longer available and impossible to add to list, so OT selected)

2 St Oswald Tr Ot (Unspecified)  (Opening an existing file in new WinREG)

3 St Oswald Ot (Unspecified) (Starting a new file in new WinREG)

I have amended them in Notepad.

Please could something be done about this problem? Thanks.     

![Screenshot](http://www.freereg.org.uk)

**Comment by EmJayFry** [comment] 2015-11-23 14:31
On 23 Nov 2015 3:50 PM, FreeUKGenIssues wrote:

> 1 St Oswald (TR)
> (TR no longer available and impossible to add to list, so OT selected)
> 2 St Oswald Tr Ot (Unspecified) (Opening an existing file in new WinREG)
> 3 St Oswald Ot (Unspecified) (Starting a new file in new WinREG)

1) Add TR yourself
   a) Press the '+' icon - invalid record added
   b) Change the Code (TR) and the Description (Transcript)
   c) Close the window
   d) Changes are available, but won't be saved, until the program is closed down
   e) If, at step b, you press the enter key in the description field, another, 
invalid record will be added - DELETE it.

2) Can't repeat. You can change from unspecified (nothing) to any code from 
table or code to code.
     Can't change from code to nothing.

3) Can't repeat. You can't have nothing for the Register Type on a new file.

4) Unspecified should longer a valid Register Type. Can always add the 
appropriate code.

## 

Regards,
Mike Fry (Jhb)

**Comment by Captainkirkdawson** [comment] 2015-11-23 16:55
Interesting that WinReg is using the new codes. FR is not yet ready to accept them. See 561

**Comment by PatReynolds** [comment] 2015-11-24 16:19
Does this mean that people should not upload/replace until FR is ready to accept the new codes? Or that they should just be warned that correct codes will be marked as errors?

**Comment by Captainkirkdawson** [comment] 2015-11-24 17:51
No the issue is that changes to winreg should be reviewed and discussed in
the scrum.

If they had been we would have said don't do it until FR is ready and it is
not and will not be for some time given all of the other issues

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment] 2015-11-25 09:10
Agree that's why we are where we are - it's something to bring up at the
next scrum, and not repeat.  But give that it's happened, and it sounds as
if there will be some time before FR is ready for the current version of
Winreg, what do we tell transcribers/co-ordinators?

On Tuesday, 24 November 2015, Kirk Dawson notifications@github.com wrote:

> No the issue is that changes to winreg should be reviewed and discussed in
> the scrum.
> 
> If they had been we would have said don't do it until FR is ready and it is
> not and will not be for some time given all of the other issues
> 
> Kirk Dawson
> Fairmont Hot Springs, B.C.
> V0B 1L1
> 
> On Tue, Nov 24, 2015 at 9:19 AM, PatReynolds <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Does this mean that people should not upload/replace until FR is ready to
> > accept the new codes? Or that they should just be warned that correct
> > codes
> > will be marked as errors?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/640#issuecomment-159319748
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/640#issuecomment-159354616
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment] 2015-12-17 05:26
#561 addressed this by permitting all agreed codes

**Closed as completed** 2015-12-21 01:50 UTC
