### ISSUE TITLE
email UserID search Routing Error (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#48] opened 2014-11-02 19:43 UTC
Issue reported by **REGManager** at 2014-11-01 14:55:21 UTC
Time: 2014-11-01T14:53:29+00:00
Session ID: 567be9ddfedbc5b79a0417ca674e36f1
Problem Page URL: [/userid_details/selection?user=email](/userid_details/selection?user=email)
Previous Page URL: [http://test2.freereg.org.uk/manage_freeregs](http://test2.freereg.org.uk/manage_freeregs)
Reported Issue:
If I select an email address with + in it I get a Routing Error

E

**Comment by Captainkirkdawson** [comment] 2014-11-02 21:18
Duplicate of 50 (or vice versa) and fixed

**Comment by graphiclunarkid** [comment] 2014-11-05 21:54
Closing as a duplicate of #50

**Closed as completed** 2014-11-05 21:54 UTC
Labels: duplicate
