### ISSUE TITLE
Filter Contact List (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#308] opened 2015-07-24 05:26 UTC
Issue reported by **REGManager** at 2015-07-24 05:26:10 UTC
Time: 2015-07-24T05:17:47+00:00
Session ID: 51dfd54f72d79a1948fac96d42f23f2d
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
As an enhancement.  Can the Contact list be filtered for the CC to whom the message was addressed.  At present the CC sees all Contacts, most of which do not concern them.
They need to see just the ones that have been emailed and referred to them and when they have answered it they can delete it.  In this way they can check that they have answered all the ones that apply to them.  It is also a good way to ensure that all Contacts do get answered because it is very easy to think that someone else has answered one, since the report does not always go to the correct person depending on what the author was doing when the report was submitted.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2015-07-26 23:44
Duplicate of 304

**Closed as completed** 2015-07-26 23:44 UTC
Labels: duplicate
