### ISSUE TITLE
159360991 Website Problem (Rebecca Troth)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1267] opened 2020-01-20 16:56 UTC
Issue reported by **Rebecca Troth** at 2020-01-19 10:56:31 UTC
Time: 2020-01-19T10:53:52+00:00
Session ID: 48001c8ac32ea4f0e3e1bd4e9abad0cc
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Hi team,

I'm having a problem with the generated citations, if I click on one of the generated citations I get taken to a page on FreeReg with an error message in red saying something has gone wrong, could you please look into this for me. I am using the latest version of Chrome on windows 10.

Here is an example of a citation that brings up the error message 
West Meon : St John : Parish Register : "Parish Register" database, FreeREG (https://www.freereg.org.uk/search_records/5b69ae0ef493fd4f60410274 : viewed 19 Jan 2020) marriage Edward Lewis to Jessie Mager 25 Feb 1873

**Comment by Captainkirkdawson** [comment] 2020-01-20 20:25
The problem occurs if you click on the citation while still having an active search.
We detected this problem and are deploying a fix in the next software release of FreeREG.

**Comment by Captainkirkdawson** [comment] 2020-01-20 20:28
Duplicate of #2166

**Comment by PatReynolds** [comment] 2020-01-21 17:43
Closing as duplicate

**Closed as completed by PatReynolds** 2020-01-21 17:43 UTC
