### ISSUE TITLE
Firefox Tracking Problem - needs review in November 210981242 Website Problem (Tim Suche)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1445] opened 2021-09-07 22:28 UTC
Issue reported by **Tim Suche** at 2021-09-07 21:54:02 UTC
Time: 2021-09-07T21:52:34+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Hi, doing research from Canada, I am having issues with your website in that 90% of the times after my initial search I click on view for a record an its dead...does not open the link. if I rgt-click and select open in new tab it works. I have to do this for all your buttons to get it to open to the record or function selected. I'm using Firefox ver 92. works fine on Free BMD and all other sites. I have disabled my ad blocker and my Enhanced tracking blocker is off. (don't have to do that for other websites) Cleared my history and cash and refreshed my screen after doing so... same issue remains
ThnX

**Comment by Captainkirkdawson** [comment] 2021-09-08 20:11
The issue is caused by Firefox Enhanced Tracking Blocker as we use of MM to show adverts on the record detail page and their code does tracking. This was observed first with version 91 of Firefox. It has continued with version 92 and will likely continue with future versions. I live in Canada and location is not the issue.
If you use the standard setting the site functions as expected.
![strict.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/eec0b3a3-60e2-401b-a48f-6201e847f710)
If you use enhanced it will no longer action the View detail link.
It can be turned off for the Freereg sit by following the instructions noted in the link in the above image and copied below.
![turn off.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/2c1ba2e6-826b-4cfc-b32f-872c0a7680f5)
I have done that and the view link works again.
@AlOneill you may want to add this to the help with a prominent placing of a link to the information as this is likely to continue.
@PatReynolds you may wish to consider removing this advert if it is not generating much revenue.
@SteveBiggs can you feedback to the user.

**Comment by suffolkroots** [comment] 2021-09-09 08:30
@Captainkirkdawson I use standard setting for enhanced tracking and I still need to turn it off. Strange that FreeCEN does not have this problem.

**Comment by SteveBiggs** [comment] 2021-09-09 12:55
@Captainkirkdawson In the problem description above, Tim Suche states  "I have disabled my ad blocker and my Enhanced tracking blocker is off." so that is not the cause in his case.

**Comment by Captainkirkdawson** [comment] 2021-09-09 15:02
@suffolkroots Not strange at all; neither displays an advert from MM on that page. Cen also does not use MM for adverts
@SteveBiggs see comment by @suffolkroots above that she still has to turn it off  even with standard

**Comment by SteveBiggs** [comment] 2021-09-09 15:09
@Captainkirkdawson I read it that the user has turned it off so doesn't matter whether Standard or Strict, but maybe I misread so I will check with him.

**Comment by suffolkroots** [comment] 2021-09-09 15:15
@Captainkirkdawson If Cen and Reg are the same in this respect, why is Reg the only one with the problem please?

**Comment by SteveBiggs** [comment] 2021-09-09 15:46
Message from user:
"I disabled it,cleared my cash and cookies, then returned to the site with no change. On some occasions it would work briefly an then not. Dispite that using Ctl RClk (new tab) on my mouse seems to work consistently. So I was still able to do search and get results and info I was looking for. Great resource by the way and much easier to get local parish info. Good Job"

At least he's still happy though!

**Comment by Captainkirkdawson** [comment] 2021-09-10 14:28
@suffolkroots Reg displays adverts on the results details page in a block next to the results. The advert is generated by MM and uses tracking cookies hence the issue with Firefox in releases 91 and into the future.  Cen does not display such adverts (there is no space) hence no tracking cookies and hence no problem with firefox

**Comment by PatReynolds** [comment] 2021-09-15 16:55
@PatReynolds to talk ot Monetizemore (FreeREG is the only ap with and advert on record details). - remove from that page?

**Comment by Captainkirkdawson** [comment] 2021-09-15 20:55
I have experimented further and found that Enhanced Tracking Protection MUST be turned off for FreeREG to function correctly even with the ad removed. If tracking protection is enabled then no link works works on any page INCLUDING the  the main navigation buttons. This is unique to FreeREG. Hence I have decided not to remove the advert since it will not help.

**Comment by PatReynolds** [comment] 2021-09-16 09:16
Many thanks, @Captainkirkdawson

**Comment by PatReynolds** [comment] 2021-09-16 11:14
Link from result to detail failed (report sent to webmaster) - search was for Smith, Berse, any date:
Esobela SMITH | Aberdeenshire | Birse | 1798 | 1861 | Aberdeenshire | Birse

https://test3.freecen.org.uk/search_records/590271c9e9379091b1f7c57f/john-smith-1841-angus-forfarshire-montrose-1760-?locale=en 
https://test3.freecen.org.uk/search_records/590285b1e9379091b1496ec9/john-smith-1851-bute-kilmory-1816-?locale=en
https://test3.freecen.org.uk/search_records/5902e8a1e9379091b1d6f3eb/john-smith-1861-dumfriesshire-tundergarth-1785-?locale=en
https://test3.freecen.org.uk/search_records/590474eee9379091b144aeb9/john-smith-1871-selkirkshire-galashiels-1826-?locale=en
https://test3.freecen.org.uk/search_records/59028a93e9379091b15d2ce0/john-smith-1881-caithness-latheron-1847-?locale=en
https://test3.freecen.org.uk/search_records/59028b2de9379091b15f9737/john-smith-1891-caithness-thurso-1879-?locale=en

Please let me know if further testing is needed or specific tests.

**Comment by Captainkirkdawson** [comment] 2021-09-16 15:05
As you know the code for REG and REG is essentially the same. The only difference between them is that REG uses MM ads and CEN does not.

With firefox enhanced tracking security the menu links on CEN work; On REG they do not. REG uses MM ad while CEN does not
![reg firefox.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/b574bf60-10a5-4c95-86a7-d1dd190a5bd4)![cen firefox.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/bc39b240-46a8-4786-bdf1-f02d73776e66)

**Comment by suffolkroots** [comment] 2021-09-16 15:13
There is one other difference beteween CEN and REG---the privacy notice has been absent for some time on CEN landing page.

**Comment by SteveBiggs** [comment] 2021-09-16 15:14
Obvious question - why can't REG use the same advert handling as CEN?

**Comment by PatReynolds** [comment] 2021-10-13 16:46
From November, FreeREG will use the same advert handling as FreeCEN (and same privacy notice).

**Comment by Irene-ene** [comment] 2021-11-10 17:42
Monitor any further problems with Firefox browser

**Comment by PatReynolds** [comment] 2021-12-08 17:32
No reports have come in, so closing (to re-open if there is any further instance).

**Closed as completed by PatReynolds** 2021-12-08 17:32 UTC
