### ISSUE TITLE
County Missing? (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#381] opened 2015-08-26 06:49 UTC
Issue reported by **MikeNL** at 2015-08-26 06:49:25 UTC
Time: 2015-08-26T06:42:05+00:00
Session ID: e65dfc4c54612d5176a4e9497a59ba9f
Problem Page URL: [/freereg1_csv_files/55dd1665f493fd928e009856](/freereg1_csv_files/55dd1665f493fd928e009856)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/55dd1665f493fd928e009857](http://freereg2.freereg.org.uk/registers/55dd1665f493fd928e009857)
Reported Issue:
On this page, the text that is created stating batch, register type, place, church ends with "of" but what is it of? I think the county name is missing.

Also, there is an inconsistency in how this text is displayed. On the page leading to this page, the variable text that has been inserted is in bold but the fixed text is unbolded. On this page, all the text is in bold.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment] 2015-08-31 17:22
Most likely this is because the Place name was not totally approved , with a Region & County label.
This will go when the CC gets all these inherited problem rationalised

**Comment by Captainkirkdawson** [comment] 2015-09-11 21:34
Duplicate of 324

**Closed as completed** 2015-09-11 21:34 UTC
Labels: Actor: county coordinator

**Comment by Sherlock21** [comment] 2015-09-12 06:53
I  have nearly completed the manual corrections to a list of 101 Place Names which don't have a County.
