### ISSUE TITLE
113060735 IG List Images does not sort or have option (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1112] opened 2018-08-01 14:59 UTC
Priority  18 (0 3 8 7)

Issue reported by **REGManager** at 2018-08-01 13:45:35 UTC
Time: 2018-08-01T13:42:40+00:00
Session ID: e2b663c733068376a3327e1d964b504e
Problem Page URL: [/image_server_images/5b606218f493fd1df7996b28/index](/image_server_images/5b606218f493fd1df7996b28/index)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5b606218f493fd1df7996b28](https://www.freereg.org.uk/image_server_groups/5b606218f493fd1df7996b28)
Reported Issue:
The images are listed in the order that they were uploaded, I think.  We need an option to sort the name column.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b61b97ff493fd1df79b8b03/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b61b97ff493fd1df79b8b03/Capture.JPG)

**Comment by Captainkirkdawson** [comment] 2018-11-27 22:49
Duplicate of $1141 or visa versa. Regardless its fixed and deployed to test3

**Closed as completed** 2018-12-05 15:43 UTC
Labels: Image Server, P18
