### ISSUE TITLE
User reports have claimed that distances given in the Nearby Feature are inaccurate. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#214] opened 2015-04-20 11:06 UTC
Issue reported by **ericb** at 2015-04-20 11:06:38 UTC
Time: 2015-04-20T11:02:13+00:00
Session ID: 2e58f4768baea72f520d8a05b2e15ae8
Problem Page URL: [/search_queries/5534daaff493fdb5c6003821](/search_queries/5534daaff493fdb5c6003821)
Previous Page URL: [http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-04-20+11%3A01%3A35+UTC&session_id=2e58f4768baea72f520d8a05b2e15ae8&user_id=ericb&problem_page_url=%2Fsearch_queries%2F5534daaff493fdb5c6003821&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fsearch_queries%2F5534daaff493fdb5c6003821%2Fabout&feedback_type=issue](http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-04-20+11%3A01%3A35+UTC&session_id=2e58f4768baea72f520d8a05b2e15ae8&user_id=ericb&problem_page_url=%2Fsearch_queries%2F5534daaff493fdb5c6003821&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fsearch_queries%2F5534daaff493fdb5c6003821%2Fabout&feedback_type=issue)
Reported Issue:
This record raised to answer the claim and suggest way forward.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment] 2015-04-20 11:12
Having tried various online calculators for finding the distance between 2 places, and I get different results depending which application is used. Not surprising really.

The "worst " one uses Place names and - suggess we might be 2 or 3 miles out.

Consider these two pairs of places ( locations are from FR2):-

From the south coast:-
Antony (CON) at GridRef SX399547, Lat 50.370361, Lon -4.252677 
and Ashburton (DEV) at GridRef SX750750, Lat 50.516402, Lon -3.7644927

FR2 gives 23 miles apart
MovableTypeScripts site which uses OS GridRef gives 23.93 miles
andrew.hedges.name site  which uses the Haversine method gives 23.75 miles
glowstar website which uses Place Names gave 24.33 miles.

xxxxxxx

from Scotland in order to get a spread of the effects of  latitude:-

Kippen (STI) at GridRef NS650940, Lat 56.119595, Lon -4.173005
and Moonzie (FIF) at GridRef NO340170, Lat 56.340737, Lon -3.0692381

FR2 gives 45 miles apart,
MovableTypeScripts site which uses OS GridRef gives 45.45 miles
andrew.hedges.name site  which uses the Haversine method gives 45.1 miles
glowstar website which uses Place names gave 48 miles.

SO, my conclusion is that it depends upon how you define your Place Locations.
We are using OS GridREfs, converted to Lat/Lon and then I suspect you are essentially using the Haversine method  since you are not compensating for the global non-spehricalness.

Your present method could not be significantly improved upon. We are not in the space travel game, and I suggest its not worth the effort of pursuing it further.

**Comment by EmJayFry** [comment] 2015-04-20 11:29
On 2015/04/20 13:12 PM, Sherlock21 wrote:

> Having tried various online calculators for finding the distance between 2
> places, and I get different results depending which application is used. Not
> surprising really.

I don't think it matters too much, so long as there's consistency in the errors.

## 

Regards,
Mike Fry (Jhb)

**Comment by benwbrum** [comment] 2015-04-20 11:30
Eric and I have discussed this offline, and as Eric reports, we're not planning to change the distance calculation algorithm.  However, we should revise our presentation of the distances, since the decimal implies precision -- which is no good without accuracy!

The product TODO is: do further rounding on distances so that we are not presenting decimals in distances.  Possibly add approximation wording: `ca. 23 miles` is preferable to `23.4 miles`, though I'm not in love with the `ca.`.

Slating for 1.4, unless we get more complaints.  It's a quick fix, and can be done by anyone.

**Comment by Sherlock21** [comment] 2015-04-20 11:53
If any change is to be made, I suggest the legend on the About page which shows the distance, to say:
(about 23 miles) etc rather than Ben's (ca. 23 miles) for the same reason that Ben doesn't like ca.

**Comment by Captainkirkdawson** [comment] 2018-02-10 17:11
IMO the single decimal place is appropriate. 
Do we leave as is or drop the decimal point.?

**Comment by Sherlock21** [comment] 2018-02-10 17:35
I am content with the accuracy  of the search.
I don't think it matters too much whether we do or do not have a decimal place.
SO if you need the space in the display, round off in the usual manner - i.e. ).5 and greater =round UP. Else round down.

IF you don't need the space, copse the story.

**Comment by AlOneill** [comment] 2018-02-20 16:50
(Missed this before it was closed)

I have 2 suggestions: 
* show distances rounded to 2 significant figures, so 1.3 but 13 — more appropriate in context
* put a very brief note re limitations of distance method in Help

**Comment by Captainkirkdawson** [comment] 2018-02-24 05:39
I am afraid that significant figures are a complex subject and I suspect we would never agree and be able to generate a common understanding. Scientifically 2500.  25 and .25 all have 2 significant figures.
Nor do I understand what the limitations are that you would document.
Is it worth the effort??

**Comment by Sherlock21** [comment] 2018-02-24 08:03
I would leave things exactly as they are. It is performing exactly as designed. (And it was I who designed it).
There were no real examples of failure with the story, and anyway: it depends upon where one determines the 'centre' of a Place to be. Its meant to be "Nearby" after all.
There must be other matters that are more worthy of attention too.

**Comment by AlOneill** [comment] 2018-02-24 12:26
I am not a geographer and do not know how our distances are calculated, so admit that the *2*  of 2 sig. figs is both arbitrary (not derived from knowledge of algorithm) and may not be appropriate across range of values that we are likely to use . However, quoting all values to 1 dp implies an *accuracy* that is surely not justified. (I do know that geographers and mathematicians look at some things rather differently, e.g. gradients, so will defer to anyone with better geographical understanding!) 

Speaking mathematically, sig. figs are useful in situations where degree of rounding that is appropriate depends on absolute size of raw value, which is what we have here, yes: the bigger the raw value, the further out it is likely to be, in absolute terms, whatever the actual algorithm used.

So,  look at raw value:
* if less than 1, round to 2 dp (or treat as for less than 10)
* else if less than 10, round to 1 dp
* else if less than 100, round to nearest integer
* else if less than 1000, round to nearest 10 (&c.)

The limitations are that exact location of centre of a given place is based on a judgement; then algorithm which calculates distance makes assumptions about shape of surface of planet.

**Comment by PatReynolds** [comment] 2018-02-24 13:46
I agree with Alison: precision gives an illusion of accuracy. I would place in 1.7 and see then if this is still an issue for our users. It may well have been overtaken by other work relating to geography.

**Comment by Captainkirkdawson** [comment] 2018-02-24 15:01
What is wrong with our current displays????????
![search2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb919b31818bfbcda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8318b500bf21824b8db2b88f4bc1e13d37aa.JPG)
![search1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb919b31818bf8cda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8316b500bf21824b8db2b88f4bc2ed3b37aa.JPG)
![distance.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46ec9d8937838daa8aabf301b44fff9e2c4533317346f6787586e22de61b2f595f581ca9415a5f44fdfadc2ba5e02e6c981e5ab38532022d8c6853beb2901eb80bbb258a4681beb88e49c7e9352cf5c6.JPG)

**Comment by Sherlock21** [comment] 2018-02-24 15:56
The calculation is linear distance on the surface of the earth, between 2 points defined by Lat/Lon to 6 decimal places, where the Lat/Lon ref is the "centre" of the Place name concerned.
In reality, we rarely get this distance to be more than 45 miles. And the decision on the Point Location is often  not to the nearest half mile, due to nature of either converting from an OS Grid Ref which itself was the 100m square in which the Place Centre sits, and which is to 4 digits anyway.
So really, if there was an error behind the original values that were complained of ( not specified so far as I can tell), its more than likely that it was an error in the original Grid Refs used, than in the Circle Maths of the calculation of ground distance between 2 points.

We are not navigating to Outer Space here after all.

**Comment by AlOneill** [comment] 2018-02-24 16:20
Example: search for WARD in Thurso, CAI. Additional Places include Olrig (4.8 miles) and North Ronaldsay (66.0 miles)

A stated distance of 4.8 miles implies the actual figure is between 4.75 and 4.85 miles. Probably reasonable enough. However, a stated 66.0 implies the actual distance is between 65.95 and 66.05 miles — far less likely. A stated distance of 66 miles would imply less precision, with the actual figure being between 65.4 and 66.5 miles. This could still be misleading, but less so.

How much does it matter? I will leave that for others to decide — @Sherlock21 I'm having trouble absorbing your explanation, so I've not taken that into account. Over and out.

**Comment by suffolkroots** [comment] 2018-02-25 08:28
If you were cops I'd ask "shouldn't you be out catching criminals?" 
It's OK as it is, perhaps "about" or "approximately" would help.
For goodness sake move on.

**Comment by Captainkirkdawson** [comment] 2018-02-26 05:21
I agree with  suffolkroots

**Comment by Captainkirkdawson** [comment] 2018-03-10 23:45
Why can't we close this

**Closed as completed** 2018-03-14 17:02 UTC
