### ISSUE TITLE
Website Problem (Stuart Tokely)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#237] opened 2015-05-31 01:41 UTC
Issue reported by **Stuart Tokely** at 2015-05-31 01:41:18 UTC
Time: 2015-05-31T01:39:36+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
Sorry, must have had a senior moment with my previous message which was ......

Using the old search engine, when searching for baptisms for 1810 in Norfolk for the surname Salmon, the baptism of Susanna Manship (born 15/1/1810 and baptised 18/1/1810) whose mother's surname is shown as Manship is found. However, the new search engine does not find this.

Ooopsy - I should have said that "whose mother's surname is shown as Salmon".    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2015-05-31 14:32
Duplicate of 229

**Closed as completed** 2015-05-31 14:32 UTC
Labels: duplicate
