### ISSUE TITLE
60534430 log off time (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#856] opened 2016-12-03 18:47 UTC
Issue reported by **deo123** at 2016-12-01 15:07:10 UTC
Time: 2016-12-01T15:06:24+00:00
Session ID: 3997bc07e1e220a8462dce42244c6def
Problem Page URL: [/manage_counties/select_action?county=Cornwall](/manage_counties/select_action?county=Cornwall)
Previous Page URL: [http://www.freereg.org.uk/registers/54081e21eca9eb81e2a4d00a](http://www.freereg.org.uk/registers/54081e21eca9eb81e2a4d00a)
Reported Issue:
Hi,
just lately after about 10 minutes I get logged off FreeREG.

I cannot do any checking of files and date name etc.

Is there anything to be done about this please. I thought we had 2 hours which isn't too bad, but not 10 minutes this is silly.

Regards Doreen    

![Screenshot](http://www.freereg.org.uk)

**Comment by dougkdev** [comment] 2016-12-03 20:31
The session time limit was shortened when there was an issue with userids getting mixed up within a session.  That bug was caused by a something else not related to the session timeout, so there is no longer a reason to have such a short timeout.  Can be lengthened to as long as is reasonable (even many hours or days) without a problem.

**Comment by ghost** [comment] 2016-12-11 16:30
Hi Doreen



I wanted to let you know that the resolution for this issue will be in a
future update of the website. ​I regret that I cannot give you a precise
time that this will be, but rest assured it is in hand.



I will be closing this thread down now.



Thank you again for taking time to give your feedback



Kind regards

Sandra
​

_________________________________________________________________________________

Sandra Adams-West
*FreeREG Communications Coordinator*
*__________________________________________________________________________________*

**Comment by Captainkirkdawson** [comment] 2016-12-12 02:01
Doug
The session limit was raised to 240 minutes for managers some time ago unless refinery is doing something stupid again

**Comment by Captainkirkdawson** [comment] 2016-12-12 23:45
Have experimented this PM. Cannot duplicate any short term timeouts. However suspect an issue could be created by having multiple windows open on FR at the same time and swapping between those windows causing an apparent timeout problem

**Comment by richpomfret** [comment] 2017-01-04 14:55
To document i.e. inform users that they will be logged out in separate tabs/windows. @AlOneill

**Comment by AlOneill** [comment] 2017-01-05 20:03
@richpomfret 
Not convinced that explanation is needed here (or that I *can* explain concisely and clearly!). Doreen was likely working on pages only accessible to a logged-in user, and her use of "just lately" *could* mean, "recently-ish, but not today".

Will give it a shot if deemed necessary, of course, but ...

**Comment by Captainkirkdawson** [comment] 2017-01-06 01:06
I think that ww could put a short note on the coordinators help.

Inactive time logout.

Please be aware that if you use multiple tabs open with each one showing a Member page, you may be logged out based on any one of pages being inactive,

**Comment by AlOneill** [comment] 2017-01-07 17:50
Thanks, Kirk. I get it now.

**Comment by AlOneill** [comment] 2017-01-07 18:11
Does this describe the situation accurately?

"Be aware that you could get unexpectedly timed out if you have more than one Members-only page open at the same time. If you are inactive on one such page for longer than the maximum time allowed, you will be timed out based on your inactivity on that page. (This does not apply to the Coordinator/Transcriber Help pages.)"

**Comment by AlOneill** [comment] 2017-01-07 18:24
Or perhaps:

"... (This does not apply to the Coordinator/Transcriber Help pages, unless these are the *only* pages you have open.)

**Comment by Captainkirkdawson** [comment] 2017-01-07 18:56
Applies to all pages after login and so it does apply to the help pages for
coordinators and transcribers as well. Since they are accessible only when
logged in

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by AlOneill** [comment] 2017-01-07 19:10
Thanks, Kirk. I guess I think about Coord/Transcriber Help pages differently, as they *are* accessible when *not* logged in, if you know the address!!

**Comment by AlOneill** [comment] 2017-01-07 19:20
Done:
http://www.freereg.org.uk/cms/information-for-coordinators/coordinator-actions

**Comment by Captainkirkdawson** [comment] 2017-01-07 19:28
Perfect

**Closed as completed by Captainkirkdawson** 2017-01-07 19:28 UTC
Labels: invalid, Actor: syndicate coordinator
