### ISSUE TITLE
Misspelling on User profile

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKRegProductIssues#1065] opened 2018-04-26 14:03 UTC
Acknowledge misspelled

**Comment by DeniseColbert** [comment] 2018-04-26 14:03
![image](https://user-images.githubusercontent.com/19173257/39310671-efe2ba32-4962-11e8-944a-7f8136e18a58.png)

**Comment by Captainkirkdawson** [comment] 2018-04-26 14:21
Duplicate of story 1058

**Closed as completed by Captainkirkdawson** 2018-04-26 14:21 UTC
