### ISSUE TITLE
County of Yorkshire (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#79] opened 2014-11-23 09:31 UTC
Issue reported by **ericb** at 2014-11-23 09:31:11 UTC
Time: 2014-11-23T09:22:52+00:00
Session ID: 13c4b61f6d0fcf4603f34f9e47fe08c1
Problem Page URL: [/places](/places)
Previous Page URL: [http://test2.freereg.org.uk/manage_counties/select_action?county=YKS](http://test2.freereg.org.uk/manage_counties/select_action?county=YKS)
Reported Issue:
There is an issue with this County. There are no places or therefore batches linked to it. 
The County Code either needs taking out of the County Names list, OR a bit of code writing that gets all of the Places & Records for the 3 ridings - ERY, NRY + WRY - since that's where the place names and the data is held.
I prefer the latter of these.

If you want a separate not in the Extra Features file for option 2, I will do one. Else it is a snag as it stands.
The effect apples in SEARCH as well as in Manage Counties.
Does this also apply to the REgion names ENGLAND, SCOTLAND & WALES where they appear in the search county pick list ?    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment] 2014-11-23 14:25
Countries do appear in county pick lists and there are no entries,

**Comment by Sherlock21** [comment] 2014-11-23 14:33
Indeed. But i am suggesting that's illogical. 
Either populate then as suggested above, 
Or, If we are not going to populate them, then I am suggesting we take them out of the list instead of confusing all the Researchers.

**Comment by benwbrum** [comment] 2014-11-24 01:59
I think I'm with Eric here.  The region/country names England, Scotland, and Wales do not actually do anything at present, and I feel like we should make a decision there, as well as of in Yorkshire.

Yorkshire could be accommodated by adding special code for expanding YKS => [ERY,WRY,NRY] within the code, and the benefits (to my mind) might be worth the effort.  

But what about "England"?  I see three possibilities:
- Eliminate "England" and the other countries as menu options.
- Convert "England" and other countries into display-only elements using HTML OptionGroups to aggregate the constituent counties into a hierarchy within the display list.  Those options would not, however, be selectable on their own.
- Make "England", "Scotland", and "Wales" act like we've proposed for Yorkshire -- expand queries on those options into all of their constituent counties.  The down-side is that that would require the search form on the researcher's browser to fetch and render every single place for which we have data in "England" or "Wales".  This has proven to be a major performance problem in the past.

**Comment by Captainkirkdawson** [comment] 2014-11-24 04:54
Me too! on accepting there is an issue that needs addressing.

Not sure there is a need for country level searching that would justify the
performance impacts so would be inclined to remove until there is a clear
use,

As for Yorkshire I was under the impression that Yorkshire actually has a
small number of places that are considered unique and that Yorksire is not
simply the 3 parts.

Do we really want to get into regional conglomerations there are many we
could identify; East Anglia, Midlands, East Midlands etc etc?

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment] 2014-11-24 09:33
Now Ben has written it out in this manner, i agree they are similar but not equal issues.
I would like Yorkshire to be used as  BenB suggests.
But lets drop England, Wales & Scotland for the  county names list because: A) the quantities get too big and b) if the researcher wants the whole of England, then let them take ALL counties option so long as they have the Names fields in the search - so as not to try and 'get' the whole of the database!
answer to Kirks' point is in next email.

ericb
I support

**Comment by Sherlock21** [comment] 2014-11-27 15:33
I did reply to Kirk's queries about some places in Yorkshire not being in any of the Ridings - includingYork itself. But that reply seems not to have got into this thread. So here it is again.

The Ainsty of York comprises 21 villages around York and was associated with the City of York - which itself was NOT in any of the Ridings of Yorkshire. In 1835, under the Municipal Reform Act,  the Ainsty was disassociated from York,  and individual Villages were put into the West Riding and the City of York put into the North Riding.
For In FreeReg1, some of the Ainsty villages were places in the County of Yorkshire - but not all were. There was/is no County code for The Ainsty unless one uses Yorkshire but this is not consistent, since all the contents of the 3 Ridings are also in theYorkshire County.

In FreeReg2, having been requested not to recreate  The Ainsty as a separate entity, I have put the Ainsty Villages into the relevant Ridings along with York City. Hence there are no places just in Yorkshire in FR2.
However, as said before, the logical was forward would be to leave the County Code of YKS  and populate it as Ben suggests with a bit of summary coding.

The treatment of Regional Codes (in #90) are different to this case, and a decision on one should not necessarily be applied to both issues.

**Comment by benwbrum** [comment] 2014-11-27 15:37
Thanks, Eric -- that's a great deal clearer than what I was thinking.

**Comment by benwbrum** [comment] 2015-02-15 13:25
The Yorkshire issue has come up again -- I think we need to research what would be involved in supporting it, and consider it for a future version.

**Comment by benwbrum** [comment] 2015-02-15 13:28
Reviewing the source code, I think that we will have some work making `chapman_code` an array so that records in NRY would contain `[NRY, YKS]` and match queries for `NRY` or `YKS`.  That's the approach which would support arbitrary hierarchies (Countries or Regions).

However, we could do a Yorkshire-only approach and modify `search_query` to convert any search on `YKS` to a search on each of the constituent ridings.  That might even be achievable for version 1.1

**Comment by Sherlock21** [comment] 2015-02-15 15:51
Ben I have written a few email comments in the other View exchanged area today, but now you have put this above response in here, I record here that I would strongly go for the approach in your second para. That is exactly what I had in mind. AND all the Transcriptions will fit that method.

**Comment by Captainkirkdawson** [comment] 2015-03-26 23:39
Really is a duplicate of 24

**Comment by edickens** [comment] 2015-03-29 08:20
This came in today...
I use FreeREG and have contributed Somerset transcriptions.

As a user, I find it very irritating that Yorkshire is split.  99 times out of 100 I know that a subject had a Yorkshire connection but have no idea which Riding I should enter.

I'm sure I'm not alone in this.

Why split Yorkshire?

If you must, why not keep them as they are but also combined under "Yorkshire"?

Brian Jones

**Comment by Sherlock21** [comment] 2015-03-29 12:57
Ben's note ( fourth item down) refers to a previous discussion Ben & Myself had on my suggested solution to the issue of Ridings & County of Yorkshire. - which is what's needed to satisfy Eric Dickens' correspondent's input circulated this morning: (comment above this one).
Its clearly an issue with some transcribers so why can't you write my suggested bit of code and satisfy them once and for all?

EricB

**Comment by FreeUKGenIssues** [comment] 2015-03-29 13:54
I also favor the YKS -> [NRY, WRY, ERY] expansion in the search code, but
think we should address that a bit later, after we work out kinks in the
deployment.  We're just too close to our release date to be modifying the
search engine code right now.

**Closed as completed** 2015-06-18 16:50 UTC
Labels: enhancement
