### ISSUE TITLE
Can't select required ID Firefox this time (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#475] opened 2015-10-11 17:35 UTC
Issue reported by **alsibk** at 2015-10-11 17:35:56 UTC
Time: 2015-10-11T17:32:53+00:00
Session ID: 394c345b4bc08671a8a606d89eb31d75
Problem Page URL: [/csvfiles/55f24141f493fd7f49078800/edit](/csvfiles/55f24141f493fd7f49078800/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/55f15d79f493fd28fe000104/by_userid](http://freereg2.freereg.org.uk/freereg1_csv_files/55f15d79f493fd28fe000104/by_userid)
Reported Issue:
Can't replace file as can't select ID.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444584956-30251-6512/ID_screen_6.jpg)

**Comment by Captainkirkdawson** [comment] 2015-10-12 02:47
Duplicate of 474

**Closed as completed** 2015-10-12 02:48 UTC
Labels: duplicate
