### ISSUE TITLE
164902598 GLA is in the list of Counties with images available but there are none (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1288] opened 2020-03-23 15:56 UTC
Part of same work as 1289
Issue reported by **REGManager** at 2020-03-23 14:16:38 UTC
Time: 2020-03-23T14:14:20+00:00
Session ID: 8ee63296ec7a4ca2f851de2f7ca77363
Problem Page URL: [/assignments/select_county?locale=en](/assignments/select_county?locale=en)
Previous Page URL: [https://www.freereg.org.uk/assignments/5462b414e937907d7000035c/list_assignments_of_myself?locale=en](https://www.freereg.org.uk/assignments/5462b414e937907d7000035c/list_assignments_of_myself?locale=en)
Reported Issue:
GLA has a lot of image groups but none have Unallocated images.  It  needs to come off this list.
See attached.
https://www.freereg.org.uk/uploads/feedback/screenshot/5e78c4c6f493fd3b45e57e06/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment] 2022-06-15 15:42
@edickens will check to see if this is still an issue

**Comment by edickens** [comment] 2022-06-16 07:03
Not fixed.  GLA is still in the list of counties as having image groups waiting to be transcribed, but there aren't any.

![Capture4.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/277bcd4e-4242-465c-ac17-1dc5b3243501)
i

**Comment by edickens** [comment] 2022-06-16 07:08
The problem is actutally more complicated.  If you select Manage Counties, and GLA, then List Unallocated Image Groups, a lot comeup.  But there are no images in these groups.  They have just been created probably because images are available elsewhere.  So it is the List Unallocated Image Groups which is wrong.

**Comment by PatReynolds** [comment] 2022-07-19 16:30
Hello @edickens - my apologies, I've forgotten what I was supposed to be doing - was it contact Vino and ask her to take a look?

**Comment by edickens** [comment] 2022-07-19 20:04
Hi Pat.  Yes.  Vino needs to see why GLA is still there when there are no available image groups.

**Comment by DeniseColbert** [comment] 2022-12-21 15:36
@Vino-S found a place called Nash with 50 unallocated images in the databases. The system knows that GLA has images but they're not being pulled through to the frontend. @Vino-S to look into it some more.

**Comment by DeniseColbert** [comment] 2023-01-25 15:14
Ready to be added to test 3

**Comment by DeniseColbert** [comment] 2023-02-15 15:39
@edickens to check

**Comment by edickens** [comment] 2023-02-15 16:20
There are images for GLA Nash on Test 3, but none on the live database.![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/a79de962-0606-46b6-8eea-12931e311145)
But these images do not have "Unallocated" status, unless some individual images are set as Unallocated.  This place should not be selected for being available.

**Comment by edickens** [comment] 2023-02-15 17:38
GLA isa still in the live list even though there are no images available...![Capture1.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/1a866e4e-cd45-431e-8222-ac3774202964)
Sandra is correct that there are no images available for GLA.

**Comment by DeniseColbert** [comment] 2023-03-15 15:31
Some more investigation into why GLA is in the list on live, when there are no images available

**Comment by DeniseColbert** [comment] 2023-06-07 14:44
@edickens to test on live

**Comment by edickens** [comment] 2023-06-07 15:47
Yes.  That looks fine.  I can't tell if it keeps a County when it runs out of Available image groups, but I am sure someone will tell us.  The sequence of Counties is also correct now.
This can be closed.

**Comment by DeniseColbert** [comment] 2023-07-05 14:12
Thanks all, closing

**Closed as completed by DeniseColbert** 2023-07-05 14:12 UTC
Labels: P19
